import type { AuthPrincipal } from '../auth/jwt.strategy';
import { CreatePromotionDto, PromotionQuoteDto, UpdatePromotionDto } from './promotions.dto';
import { PromotionsService } from './promotions.service';
export declare class PromotionsPublicController {
    private readonly promotions;
    constructor(promotions: PromotionsService);
    quote(user: AuthPrincipal | undefined, dto: PromotionQuoteDto): Promise<{
        subtotal: number;
        customerLimitVerified: boolean;
        validUntil: Date | null;
        id: string;
        code: string;
        name: string;
        discount: number;
        eligibleSubtotal: number;
    }>;
}
export declare class PromotionsAdminController {
    private readonly promotions;
    constructor(promotions: PromotionsService);
    list(): Promise<{
        effectiveStatus: "active" | "draft" | "paused" | "expired" | "scheduled";
        redemptionCount: number;
        _count: undefined;
        id: string;
        name: string;
        code: string;
        description: string | null;
        createdBy: string;
        status: import(".prisma/client").$Enums.PromotionStatus;
        createdAt: Date;
        updatedAt: Date;
        updatedBy: string;
        startsAt: Date | null;
        endsAt: Date | null;
        discountType: import(".prisma/client").$Enums.PromotionDiscountType;
        discountValue: number;
        maxDiscount: number | null;
        minimumSubtotal: number;
        eligibleProductIds: string[];
        eligibleCategories: string[];
        totalLimit: number | null;
        perCustomerLimit: number | null;
    }[]>;
    create(user: AuthPrincipal, dto: CreatePromotionDto): Promise<{
        effectiveStatus: "active" | "draft" | "paused" | "expired" | "scheduled";
        id: string;
        name: string;
        code: string;
        description: string | null;
        createdBy: string;
        status: import(".prisma/client").$Enums.PromotionStatus;
        createdAt: Date;
        updatedAt: Date;
        updatedBy: string;
        startsAt: Date | null;
        endsAt: Date | null;
        discountType: import(".prisma/client").$Enums.PromotionDiscountType;
        discountValue: number;
        maxDiscount: number | null;
        minimumSubtotal: number;
        eligibleProductIds: string[];
        eligibleCategories: string[];
        totalLimit: number | null;
        perCustomerLimit: number | null;
    }>;
    update(user: AuthPrincipal, id: string, dto: UpdatePromotionDto): Promise<{
        effectiveStatus: "active" | "draft" | "paused" | "expired" | "scheduled";
        id: string;
        name: string;
        code: string;
        description: string | null;
        createdBy: string;
        status: import(".prisma/client").$Enums.PromotionStatus;
        createdAt: Date;
        updatedAt: Date;
        updatedBy: string;
        startsAt: Date | null;
        endsAt: Date | null;
        discountType: import(".prisma/client").$Enums.PromotionDiscountType;
        discountValue: number;
        maxDiscount: number | null;
        minimumSubtotal: number;
        eligibleProductIds: string[];
        eligibleCategories: string[];
        totalLimit: number | null;
        perCustomerLimit: number | null;
    }>;
    activate(user: AuthPrincipal, id: string): Promise<{
        effectiveStatus: "active" | "draft" | "paused" | "expired" | "scheduled";
        id: string;
        name: string;
        code: string;
        description: string | null;
        createdBy: string;
        status: import(".prisma/client").$Enums.PromotionStatus;
        createdAt: Date;
        updatedAt: Date;
        updatedBy: string;
        startsAt: Date | null;
        endsAt: Date | null;
        discountType: import(".prisma/client").$Enums.PromotionDiscountType;
        discountValue: number;
        maxDiscount: number | null;
        minimumSubtotal: number;
        eligibleProductIds: string[];
        eligibleCategories: string[];
        totalLimit: number | null;
        perCustomerLimit: number | null;
    }>;
    pause(user: AuthPrincipal, id: string): Promise<{
        effectiveStatus: "active" | "draft" | "paused" | "expired" | "scheduled";
        id: string;
        name: string;
        code: string;
        description: string | null;
        createdBy: string;
        status: import(".prisma/client").$Enums.PromotionStatus;
        createdAt: Date;
        updatedAt: Date;
        updatedBy: string;
        startsAt: Date | null;
        endsAt: Date | null;
        discountType: import(".prisma/client").$Enums.PromotionDiscountType;
        discountValue: number;
        maxDiscount: number | null;
        minimumSubtotal: number;
        eligibleProductIds: string[];
        eligibleCategories: string[];
        totalLimit: number | null;
        perCustomerLimit: number | null;
    }>;
}
