import { Prisma } from '@prisma/client';
import { AuditInput, AuditService } from '../audit/audit.service';
import { PrismaService } from '../prisma/prisma.service';
import { CreatePromotionDto, PromotionQuoteDto, UpdatePromotionDto } from './promotions.dto';
export interface PromotionLine {
    productId: string;
    sku: string;
    category: string;
    price: number;
    qty: number;
}
export interface AppliedPromotion {
    id: string;
    code: string;
    name: string;
    discount: number;
    eligibleSubtotal: number;
}
export declare class PromotionsService {
    private readonly prisma;
    private readonly audit;
    constructor(prisma: PrismaService, audit: AuditService);
    list(): Promise<{
        effectiveStatus: "active" | "draft" | "paused" | "expired" | "scheduled";
        redemptionCount: number;
        _count: undefined;
        id: string;
        name: string;
        code: string;
        description: string | null;
        createdBy: string;
        status: import(".prisma/client").$Enums.PromotionStatus;
        createdAt: Date;
        updatedAt: Date;
        updatedBy: string;
        startsAt: Date | null;
        endsAt: Date | null;
        discountType: import(".prisma/client").$Enums.PromotionDiscountType;
        discountValue: number;
        maxDiscount: number | null;
        minimumSubtotal: number;
        eligibleProductIds: string[];
        eligibleCategories: string[];
        totalLimit: number | null;
        perCustomerLimit: number | null;
    }[]>;
    create(dto: CreatePromotionDto, actor: string): Promise<{
        effectiveStatus: "active" | "draft" | "paused" | "expired" | "scheduled";
        id: string;
        name: string;
        code: string;
        description: string | null;
        createdBy: string;
        status: import(".prisma/client").$Enums.PromotionStatus;
        createdAt: Date;
        updatedAt: Date;
        updatedBy: string;
        startsAt: Date | null;
        endsAt: Date | null;
        discountType: import(".prisma/client").$Enums.PromotionDiscountType;
        discountValue: number;
        maxDiscount: number | null;
        minimumSubtotal: number;
        eligibleProductIds: string[];
        eligibleCategories: string[];
        totalLimit: number | null;
        perCustomerLimit: number | null;
    }>;
    update(id: string, dto: UpdatePromotionDto, actor: string): Promise<{
        effectiveStatus: "active" | "draft" | "paused" | "expired" | "scheduled";
        id: string;
        name: string;
        code: string;
        description: string | null;
        createdBy: string;
        status: import(".prisma/client").$Enums.PromotionStatus;
        createdAt: Date;
        updatedAt: Date;
        updatedBy: string;
        startsAt: Date | null;
        endsAt: Date | null;
        discountType: import(".prisma/client").$Enums.PromotionDiscountType;
        discountValue: number;
        maxDiscount: number | null;
        minimumSubtotal: number;
        eligibleProductIds: string[];
        eligibleCategories: string[];
        totalLimit: number | null;
        perCustomerLimit: number | null;
    }>;
    activate(id: string, actor: string): Promise<{
        effectiveStatus: "active" | "draft" | "paused" | "expired" | "scheduled";
        id: string;
        name: string;
        code: string;
        description: string | null;
        createdBy: string;
        status: import(".prisma/client").$Enums.PromotionStatus;
        createdAt: Date;
        updatedAt: Date;
        updatedBy: string;
        startsAt: Date | null;
        endsAt: Date | null;
        discountType: import(".prisma/client").$Enums.PromotionDiscountType;
        discountValue: number;
        maxDiscount: number | null;
        minimumSubtotal: number;
        eligibleProductIds: string[];
        eligibleCategories: string[];
        totalLimit: number | null;
        perCustomerLimit: number | null;
    }>;
    pause(id: string, actor: string): Promise<{
        effectiveStatus: "active" | "draft" | "paused" | "expired" | "scheduled";
        id: string;
        name: string;
        code: string;
        description: string | null;
        createdBy: string;
        status: import(".prisma/client").$Enums.PromotionStatus;
        createdAt: Date;
        updatedAt: Date;
        updatedBy: string;
        startsAt: Date | null;
        endsAt: Date | null;
        discountType: import(".prisma/client").$Enums.PromotionDiscountType;
        discountValue: number;
        maxDiscount: number | null;
        minimumSubtotal: number;
        eligibleProductIds: string[];
        eligibleCategories: string[];
        totalLimit: number | null;
        perCustomerLimit: number | null;
    }>;
    quote(dto: PromotionQuoteDto, customerId?: string): Promise<{
        subtotal: number;
        customerLimitVerified: boolean;
        validUntil: Date | null;
        id: string;
        code: string;
        name: string;
        discount: number;
        eligibleSubtotal: number;
    }>;
    evaluateForOrderOnTx(tx: Prisma.TransactionClient, input: {
        code: string;
        customerId: string;
        lines: PromotionLine[];
    }): Promise<AppliedPromotion>;
    registerRedemptionOnTx(tx: Prisma.TransactionClient, applied: AppliedPromotion, customerId: string, orderId: string, actor: string, events: AuditInput[]): Promise<void>;
    private evaluate;
    private isEligible;
    private resolveLines;
    private validatedData;
    private changeStatus;
    private requirePromotion;
    private effectiveStatus;
    private view;
    private event;
}
