import { StorefrontBlockDevice } from '@prisma/client';
import type { AuthPrincipal } from '../auth/jwt.strategy';
import { CreateStorefrontBlockDto, ReorderStorefrontBlocksDto, ScheduleStorefrontBlockDto, UpdateStorefrontBlockDto } from './storefront-blocks.dto';
import { StorefrontBlocksService } from './storefront-blocks.service';
export declare class StorefrontBlocksPublicController {
    private readonly blocks;
    constructor(blocks: StorefrontBlocksService);
    publicBlocks(device?: StorefrontBlockDevice): Promise<{
        products: import("../catalog/catalog.dto").CatalogProductDto[];
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }[]>;
}
export declare class StorefrontBlocksAdminController {
    private readonly blocks;
    constructor(blocks: StorefrontBlocksService);
    list(): import(".prisma/client").Prisma.PrismaPromise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }[]>;
    create(user: AuthPrincipal, dto: CreateStorefrontBlockDto): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    reorder(user: AuthPrincipal, dto: ReorderStorefrontBlocksDto): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }[]>;
    update(user: AuthPrincipal, id: string, dto: UpdateStorefrontBlockDto): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    publish(user: AuthPrincipal, id: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    schedule(user: AuthPrincipal, id: string, dto: ScheduleStorefrontBlockDto): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    cancelSchedule(user: AuthPrincipal, id: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    archive(user: AuthPrincipal, id: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
}
