import { Prisma, StorefrontBlockDevice } from '@prisma/client';
import { AuditService } from '../audit/audit.service';
import { ModerationService } from '../ai/moderation.service';
import { CatalogService } from '../catalog/catalog.service';
import { PrismaService } from '../prisma/prisma.service';
import { CreateStorefrontBlockDto, ReorderStorefrontBlocksDto, ScheduleStorefrontBlockDto, UpdateStorefrontBlockDto } from './storefront-blocks.dto';
export declare class StorefrontBlocksService {
    private readonly prisma;
    private readonly audit;
    private readonly catalog;
    private readonly moderation;
    constructor(prisma: PrismaService, audit: AuditService, catalog: CatalogService, moderation: ModerationService);
    list(): Prisma.PrismaPromise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }[]>;
    publicBlocks(device: StorefrontBlockDevice): Promise<{
        products: import("../catalog/catalog.dto").CatalogProductDto[];
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }[]>;
    create(dto: CreateStorefrontBlockDto, actor: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    update(id: string, dto: UpdateStorefrontBlockDto, actor: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    publish(id: string, actor: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    schedule(id: string, dto: ScheduleStorefrontBlockDto, actor: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    archive(id: string, actor: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    cancelSchedule(id: string, actor: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }>;
    reorder(dto: ReorderStorefrontBlocksDto, actor: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.StorefrontBlockType;
        createdBy: string;
        status: import(".prisma/client").$Enums.StorefrontBlockStatus;
        createdAt: Date;
        updatedAt: Date;
        body: string | null;
        updatedBy: string;
        title: string;
        startsAt: Date | null;
        endsAt: Date | null;
        tone: string;
        ctaLabel: string | null;
        publishedAt: Date | null;
        device: import(".prisma/client").$Enums.StorefrontBlockDevice;
        eyebrow: string | null;
        ctaHref: string | null;
        imageUrl: string | null;
        productIds: string[];
        position: number;
    }[]>;
    private normalized;
    private assertContentClean;
    private assertNoHeroScheduleOverlap;
    private archivePublishedHeroes;
    private changeStatus;
    private requireBlock;
    private requireBlockOnTx;
    private lock;
    private event;
}
