import { Campaign } from '@prisma/client';
import { AuditService } from '../audit/audit.service';
import { OutboxService } from '../outbox/outbox.service';
import { PrismaService } from '../prisma/prisma.service';
import { CampaignAttributionService } from './campaign-attribution.service';
import { CampaignCreativePolicyService } from './campaign-creative-policy.service';
import { CreateCampaignDto, RecordCampaignSpendDto, UpdateCampaignDto } from './campaigns.dto';
import { SegmentRules } from './segment-builder';
export interface CampaignRoi {
    campaign: Campaign;
    rules: SegmentRules;
    description: string;
    orders: number;
    revenue: number;
    budget: number;
    spend: number;
    profit: number;
    grossProfit: number;
    refundRevenue: number;
    restoredCost: number;
    netRevenue: number;
    netGrossProfit: number;
    contribution: number;
    paidRoas: number | null;
    roas: number | null;
    roiPct: number | null;
    delivery: {
        pending: number;
        sent: number;
        failed: number;
        cancelled: number;
    };
    funnel: {
        clicks: number;
        visits: number;
        checkouts: number;
        conversions: number;
        conversionRate: number | null;
    };
}
export declare class CampaignsService {
    private readonly prisma;
    private readonly audit;
    private readonly outbox;
    private readonly attribution;
    private readonly creativePolicy?;
    constructor(prisma: PrismaService, audit: AuditService, outbox: OutboxService, attribution: CampaignAttributionService, creativePolicy?: CampaignCreativePolicyService | undefined);
    preview(rules: SegmentRules): Promise<{
        rules: Required<Pick<SegmentRules, "tags" | "limit">> & SegmentRules;
        description: string;
        totalCustomers: number;
        matchedCustomers: number;
        eligibleCustomers: number;
        excludedNoConsent: number;
        audience: {
            id: string;
            name: string;
            phone: string;
            segments: string[];
            ltv: number;
            spent: number;
        }[];
    }>;
    list(): Promise<CampaignRoi[]>;
    create(dto: CreateCampaignDto, actor: string): Promise<{
        campaign: {
            promotionCode: string | null;
            id: string;
            name: string;
            createdBy: string;
            status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
            createdAt: Date;
            updatedAt: Date;
            revenue: number;
            source: string;
            channel: string;
            orders: number;
            template: string;
            updatedBy: string;
            medium: string;
            trackingCode: string;
            approvalId: string | null;
            segment: string;
            budget: number;
            creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
            creativeHeadline: string;
            creativeBody: string | null;
            creativeAssetUrl: string | null;
            creativeCtaLabel: string | null;
            destinationUrl: string;
            rejectionReason: string | null;
            approvedBy: string | null;
            reviewedAt: Date | null;
            approvedAt: Date | null;
            activatedAt: Date | null;
            pausedAt: Date | null;
            completedAt: Date | null;
            grossProfit: number;
        };
        rules: Required<Pick<SegmentRules, "tags" | "limit">> & SegmentRules;
        description: string;
        queued: number;
    }>;
    update(id: string, dto: UpdateCampaignDto, actor: string): Promise<{
        promotionCode: string | null;
        id: string;
        name: string;
        createdBy: string;
        status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
        createdAt: Date;
        updatedAt: Date;
        revenue: number;
        source: string;
        channel: string;
        orders: number;
        template: string;
        updatedBy: string;
        medium: string;
        trackingCode: string;
        approvalId: string | null;
        segment: string;
        budget: number;
        creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
        creativeHeadline: string;
        creativeBody: string | null;
        creativeAssetUrl: string | null;
        creativeCtaLabel: string | null;
        destinationUrl: string;
        rejectionReason: string | null;
        approvedBy: string | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        activatedAt: Date | null;
        pausedAt: Date | null;
        completedAt: Date | null;
        grossProfit: number;
    }>;
    submit(id: string, actor: string): Promise<{
        promotionCode: string | null;
        id: string;
        name: string;
        createdBy: string;
        status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
        createdAt: Date;
        updatedAt: Date;
        revenue: number;
        source: string;
        channel: string;
        orders: number;
        template: string;
        updatedBy: string;
        medium: string;
        trackingCode: string;
        approvalId: string | null;
        segment: string;
        budget: number;
        creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
        creativeHeadline: string;
        creativeBody: string | null;
        creativeAssetUrl: string | null;
        creativeCtaLabel: string | null;
        destinationUrl: string;
        rejectionReason: string | null;
        approvedBy: string | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        activatedAt: Date | null;
        pausedAt: Date | null;
        completedAt: Date | null;
        grossProfit: number;
    }>;
    activate(id: string, actor: string): Promise<{
        campaign: {
            promotionCode: string | null;
            id: string;
            name: string;
            createdBy: string;
            status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
            createdAt: Date;
            updatedAt: Date;
            revenue: number;
            source: string;
            channel: string;
            orders: number;
            template: string;
            updatedBy: string;
            medium: string;
            trackingCode: string;
            approvalId: string | null;
            segment: string;
            budget: number;
            creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
            creativeHeadline: string;
            creativeBody: string | null;
            creativeAssetUrl: string | null;
            creativeCtaLabel: string | null;
            destinationUrl: string;
            rejectionReason: string | null;
            approvedBy: string | null;
            reviewedAt: Date | null;
            approvedAt: Date | null;
            activatedAt: Date | null;
            pausedAt: Date | null;
            completedAt: Date | null;
            grossProfit: number;
        };
        queued: number;
        excludedNoConsent: number;
        trackingUrl: string;
    }>;
    pause(id: string, actor: string): Promise<{
        promotionCode: string | null;
        id: string;
        name: string;
        createdBy: string;
        status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
        createdAt: Date;
        updatedAt: Date;
        revenue: number;
        source: string;
        channel: string;
        orders: number;
        template: string;
        updatedBy: string;
        medium: string;
        trackingCode: string;
        approvalId: string | null;
        segment: string;
        budget: number;
        creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
        creativeHeadline: string;
        creativeBody: string | null;
        creativeAssetUrl: string | null;
        creativeCtaLabel: string | null;
        destinationUrl: string;
        rejectionReason: string | null;
        approvedBy: string | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        activatedAt: Date | null;
        pausedAt: Date | null;
        completedAt: Date | null;
        grossProfit: number;
    }>;
    complete(id: string, actor: string): Promise<{
        promotionCode: string | null;
        id: string;
        name: string;
        createdBy: string;
        status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
        createdAt: Date;
        updatedAt: Date;
        revenue: number;
        source: string;
        channel: string;
        orders: number;
        template: string;
        updatedBy: string;
        medium: string;
        trackingCode: string;
        approvalId: string | null;
        segment: string;
        budget: number;
        creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
        creativeHeadline: string;
        creativeBody: string | null;
        creativeAssetUrl: string | null;
        creativeCtaLabel: string | null;
        destinationUrl: string;
        rejectionReason: string | null;
        approvedBy: string | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        activatedAt: Date | null;
        pausedAt: Date | null;
        completedAt: Date | null;
        grossProfit: number;
    }>;
    recordSpend(id: string, dto: RecordCampaignSpendDto, actor: string): Promise<CampaignRoi>;
    recordConversion(id: string, orderId: string, actor: string): Promise<CampaignRoi>;
    roiFor(id: string): Promise<CampaignRoi>;
    private changeStatus;
    private lockCampaign;
    private sumSpend;
    private creativeInput;
    private ruleInput;
    private trackingUrl;
    private loadCustomersWithSpend;
    private roiView;
    private eligibleAudience;
    private recipientFor;
    private segmentValue;
    private customerView;
}
