import { AuthPrincipal } from '../auth/jwt.strategy';
import { CampaignConversionDto, CreateCampaignDto, RecordCampaignSpendDto, SegmentRulesDto, UpdateCampaignDto } from './campaigns.dto';
import { CampaignsService } from './campaigns.service';
export declare class CampaignsController {
    private readonly campaigns;
    constructor(campaigns: CampaignsService);
    preview(dto: SegmentRulesDto): Promise<{
        rules: Required<Pick<import("./segment-builder").SegmentRules, "tags" | "limit">> & import("./segment-builder").SegmentRules;
        description: string;
        totalCustomers: number;
        matchedCustomers: number;
        eligibleCustomers: number;
        excludedNoConsent: number;
        audience: {
            id: string;
            name: string;
            phone: string;
            segments: string[];
            ltv: number;
            spent: number;
        }[];
    }>;
    create(user: AuthPrincipal, dto: CreateCampaignDto): Promise<{
        campaign: {
            promotionCode: string | null;
            id: string;
            name: string;
            createdBy: string;
            status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
            createdAt: Date;
            updatedAt: Date;
            revenue: number;
            source: string;
            channel: string;
            orders: number;
            template: string;
            updatedBy: string;
            medium: string;
            trackingCode: string;
            approvalId: string | null;
            segment: string;
            budget: number;
            creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
            creativeHeadline: string;
            creativeBody: string | null;
            creativeAssetUrl: string | null;
            creativeCtaLabel: string | null;
            destinationUrl: string;
            rejectionReason: string | null;
            approvedBy: string | null;
            reviewedAt: Date | null;
            approvedAt: Date | null;
            activatedAt: Date | null;
            pausedAt: Date | null;
            completedAt: Date | null;
            grossProfit: number;
        };
        rules: Required<Pick<import("./segment-builder").SegmentRules, "tags" | "limit">> & import("./segment-builder").SegmentRules;
        description: string;
        queued: number;
    }>;
    update(user: AuthPrincipal, id: string, dto: UpdateCampaignDto): Promise<{
        promotionCode: string | null;
        id: string;
        name: string;
        createdBy: string;
        status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
        createdAt: Date;
        updatedAt: Date;
        revenue: number;
        source: string;
        channel: string;
        orders: number;
        template: string;
        updatedBy: string;
        medium: string;
        trackingCode: string;
        approvalId: string | null;
        segment: string;
        budget: number;
        creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
        creativeHeadline: string;
        creativeBody: string | null;
        creativeAssetUrl: string | null;
        creativeCtaLabel: string | null;
        destinationUrl: string;
        rejectionReason: string | null;
        approvedBy: string | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        activatedAt: Date | null;
        pausedAt: Date | null;
        completedAt: Date | null;
        grossProfit: number;
    }>;
    submit(user: AuthPrincipal, id: string): Promise<{
        promotionCode: string | null;
        id: string;
        name: string;
        createdBy: string;
        status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
        createdAt: Date;
        updatedAt: Date;
        revenue: number;
        source: string;
        channel: string;
        orders: number;
        template: string;
        updatedBy: string;
        medium: string;
        trackingCode: string;
        approvalId: string | null;
        segment: string;
        budget: number;
        creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
        creativeHeadline: string;
        creativeBody: string | null;
        creativeAssetUrl: string | null;
        creativeCtaLabel: string | null;
        destinationUrl: string;
        rejectionReason: string | null;
        approvedBy: string | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        activatedAt: Date | null;
        pausedAt: Date | null;
        completedAt: Date | null;
        grossProfit: number;
    }>;
    activate(user: AuthPrincipal, id: string): Promise<{
        campaign: {
            promotionCode: string | null;
            id: string;
            name: string;
            createdBy: string;
            status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
            createdAt: Date;
            updatedAt: Date;
            revenue: number;
            source: string;
            channel: string;
            orders: number;
            template: string;
            updatedBy: string;
            medium: string;
            trackingCode: string;
            approvalId: string | null;
            segment: string;
            budget: number;
            creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
            creativeHeadline: string;
            creativeBody: string | null;
            creativeAssetUrl: string | null;
            creativeCtaLabel: string | null;
            destinationUrl: string;
            rejectionReason: string | null;
            approvedBy: string | null;
            reviewedAt: Date | null;
            approvedAt: Date | null;
            activatedAt: Date | null;
            pausedAt: Date | null;
            completedAt: Date | null;
            grossProfit: number;
        };
        queued: number;
        excludedNoConsent: number;
        trackingUrl: string;
    }>;
    pause(user: AuthPrincipal, id: string): Promise<{
        promotionCode: string | null;
        id: string;
        name: string;
        createdBy: string;
        status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
        createdAt: Date;
        updatedAt: Date;
        revenue: number;
        source: string;
        channel: string;
        orders: number;
        template: string;
        updatedBy: string;
        medium: string;
        trackingCode: string;
        approvalId: string | null;
        segment: string;
        budget: number;
        creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
        creativeHeadline: string;
        creativeBody: string | null;
        creativeAssetUrl: string | null;
        creativeCtaLabel: string | null;
        destinationUrl: string;
        rejectionReason: string | null;
        approvedBy: string | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        activatedAt: Date | null;
        pausedAt: Date | null;
        completedAt: Date | null;
        grossProfit: number;
    }>;
    complete(user: AuthPrincipal, id: string): Promise<{
        promotionCode: string | null;
        id: string;
        name: string;
        createdBy: string;
        status: import(".prisma/client").$Enums.CampaignLifecycleStatus;
        createdAt: Date;
        updatedAt: Date;
        revenue: number;
        source: string;
        channel: string;
        orders: number;
        template: string;
        updatedBy: string;
        medium: string;
        trackingCode: string;
        approvalId: string | null;
        segment: string;
        budget: number;
        creativeType: import(".prisma/client").$Enums.CampaignCreativeType;
        creativeHeadline: string;
        creativeBody: string | null;
        creativeAssetUrl: string | null;
        creativeCtaLabel: string | null;
        destinationUrl: string;
        rejectionReason: string | null;
        approvedBy: string | null;
        reviewedAt: Date | null;
        approvedAt: Date | null;
        activatedAt: Date | null;
        pausedAt: Date | null;
        completedAt: Date | null;
        grossProfit: number;
    }>;
    recordSpend(user: AuthPrincipal, id: string, dto: RecordCampaignSpendDto): Promise<import("./campaigns.service").CampaignRoi>;
    list(): Promise<import("./campaigns.service").CampaignRoi[]>;
    roi(id: string): Promise<import("./campaigns.service").CampaignRoi>;
    convert(user: AuthPrincipal, id: string, dto: CampaignConversionDto): Promise<import("./campaigns.service").CampaignRoi>;
}
