export const ACCOUNTING_ACCOUNT_SEED = [
  { code: '1000', name: 'Наличные в кассе', type: 'asset' },
  { code: '1010', name: 'Расчётный счёт', type: 'asset' },
  { code: '1020', name: 'Деньги у платёжных провайдеров', type: 'asset' },
  { code: '1100', name: 'Дебиторская задолженность', type: 'asset' },
  { code: '1200', name: 'Товарные запасы', type: 'asset' },
  { code: '1300', name: 'Авансы поставщикам', type: 'asset' },
  { code: '2000', name: 'Задолженность поставщикам', type: 'liability' },
  { code: '2100', name: 'Задолженность по зарплате', type: 'liability' },
  { code: '2200', name: 'Налоги к уплате', type: 'liability' },
  { code: '2300', name: 'Обязательства по подарочным картам', type: 'liability' },
  { code: '3000', name: 'Капитал владельца', type: 'equity' },
  { code: '4000', name: 'Выручка от продаж', type: 'revenue' },
  { code: '4100', name: 'Выручка сервисного центра', type: 'revenue' },
  { code: '5000', name: 'Себестоимость продаж', type: 'expense' },
  { code: '6100', name: 'Расходы на зарплату', type: 'expense' },
  { code: '6200', name: 'Аренда', type: 'expense' },
  { code: '6300', name: 'Логистика', type: 'expense' },
  { code: '6400', name: 'Маркетинг', type: 'expense' },
  { code: '6500', name: 'Коммунальные расходы', type: 'expense' },
  { code: '6600', name: 'Расходы на закупку', type: 'expense' },
  { code: '6900', name: 'Прочие операционные расходы', type: 'expense' },
  { code: '6990', name: 'Финансовые расхождения', type: 'expense' },
] as const;
