import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsIn, IsOptional, IsString, Matches, MaxLength } from 'class-validator';

export const FCM_TOKEN_PATTERN = /^(?=.{20,4096}$)[A-Za-z0-9_:-]+$/;
export const PUSH_TOKEN_PATTERN = /^(?:(ExponentPushToken|ExpoPushToken)\[[A-Za-z0-9_-]+\]|[a-fA-F0-9]{64,200}|(?=.{20,4096}$)[A-Za-z0-9_:-]+)$/;
export const PUSH_PLATFORMS = ['ios', 'android', 'web', 'unknown'] as const;
export const PUSH_SCOPES = ['anonymous', 'customer', 'staff'] as const;

export type PushPlatform = (typeof PUSH_PLATFORMS)[number];
export type PushScope = (typeof PUSH_SCOPES)[number];

export class RegisterPushTokenDto {
  @ApiProperty({
    example: 'ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]',
    description: 'Expo, native APNs or FCM registration token.',
  })
  @IsString()
  @MaxLength(4096)
  @Matches(PUSH_TOKEN_PATTERN, { message: 'token must be an Expo, APNs or FCM push token' })
  token!: string;

  @ApiProperty({ enum: PUSH_PLATFORMS, example: 'ios' })
  @IsIn(PUSH_PLATFORMS)
  platform!: PushPlatform;

  @ApiProperty({
    example: 'ios-iphone-15-pro:8F4C5B2E',
    description: 'Stable local installation/device key generated by the native app.',
  })
  @IsString()
  @MaxLength(160)
  deviceId!: string;

  @ApiPropertyOptional({
    enum: PUSH_SCOPES,
    example: 'customer',
    description: 'Client-requested scope; authenticated JWT wins over this value.',
  })
  @IsOptional()
  @IsIn(PUSH_SCOPES)
  scope?: PushScope;
}
