import { ConfigService } from '@nestjs/config';
import { AuditService } from '../audit/audit.service';
import { PrismaService } from '../prisma/prisma.service';
import { CancelOrderLineSupplyDto, PlaceOrderLineSupplyDto } from './order-line-supply.dto';
import { UnitsService } from '../units/units.service';
export declare class OrderLineSupplyService {
    private readonly prisma;
    private readonly audit;
    private readonly units;
    private readonly config?;
    constructor(prisma: PrismaService, audit: AuditService, units: UnitsService, config?: ConfigService | undefined);
    private lockOrderForItem;
    placeSupplierOrder(orderItemId: string, dto: PlaceOrderLineSupplyDto, actor: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    markInTransit(orderItemId: string, actor: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    markReceived(orderItemId: string, actor: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    markQualityChecked(orderItemId: string, actor: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    markReady(orderItemId: string, actor: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    markHandedOver(orderItemId: string, actor: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    cancel(orderItemId: string, dto: CancelOrderLineSupplyDto, actor: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    private transition;
}
