import { AuthPrincipal } from '../auth/jwt.strategy';
import { CancelOrderLineSupplyDto, PlaceOrderLineSupplyDto } from './order-line-supply.dto';
import { OrderLineSupplyService } from './order-line-supply.service';
export declare class OrderLineSupplyController {
    private readonly supply;
    constructor(supply: OrderLineSupplyService);
    place(user: AuthPrincipal, orderItemId: string, dto: PlaceOrderLineSupplyDto): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    ship(user: AuthPrincipal, orderItemId: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    receive(user: AuthPrincipal, orderItemId: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    qualityCheck(user: AuthPrincipal, orderItemId: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    ready(user: AuthPrincipal, orderItemId: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    handover(user: AuthPrincipal, orderItemId: string): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
    cancel(user: AuthPrincipal, orderItemId: string, dto: CancelOrderLineSupplyDto): Promise<{
        idempotent: boolean;
        id: string;
        actor: string;
        status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
        createdAt: Date;
        updatedAt: Date;
        expectedAt: Date | null;
        receivedQty: number;
        orderItemId: string;
        purchaseOrderItemId: string | null;
        supplierOfferId: string | null;
        orderedQty: number;
    }>;
}
