import { Prisma } from '@prisma/client';
import { AuditService } from '../audit/audit.service';
import { PrismaService } from '../prisma/prisma.service';
import { CreateDeliverySlotDto, CreateDeliveryZoneDto, CreateStorePointDto, UpdateStorePointDto } from './logistics.dto';
export declare class LogisticsService {
    private readonly prisma;
    private readonly audit;
    constructor(prisma: PrismaService, audit: AuditService);
    availability(date?: string, zoneId?: string): Promise<{
        slots: {
            reserved: number;
            remaining: number;
            available: boolean;
            id: string;
            idempotencyKey: string;
            createdBy: string;
            createdAt: Date;
            updatedAt: Date;
            active: boolean;
            zoneId: string;
            startsAt: Date;
            endsAt: Date;
            capacity: number;
        }[];
        id: string;
        name: string;
        code: string;
        idempotencyKey: string;
        createdBy: string;
        createdAt: Date;
        updatedAt: Date;
        active: boolean;
        fee: number;
        etaMinMinutes: number;
        etaMaxMinutes: number;
    }[]>;
    checkoutOptions(date?: string): Promise<{
        pickupPoints: {
            id: string;
            name: string;
            code: string;
            hours: string;
            address: string;
            inventoryLocation: string;
            pickupInstructions: string | null;
            sortOrder: number;
        }[];
        deliveryZones: {
            slots: {
                reserved: number;
                remaining: number;
                available: boolean;
                id: string;
                idempotencyKey: string;
                createdBy: string;
                createdAt: Date;
                updatedAt: Date;
                active: boolean;
                zoneId: string;
                startsAt: Date;
                endsAt: Date;
                capacity: number;
            }[];
            id: string;
            name: string;
            code: string;
            idempotencyKey: string;
            createdBy: string;
            createdAt: Date;
            updatedAt: Date;
            active: boolean;
            fee: number;
            etaMinMinutes: number;
            etaMaxMinutes: number;
        }[];
    }>;
    resolveStorePoint(storePointId?: string, legacyAlias?: string, requireSelection?: boolean): Promise<{
        id: string;
        name: string;
        code: string;
        idempotencyKey: string;
        createdBy: string;
        createdAt: Date;
        updatedAt: Date;
        active: boolean;
        hours: string;
        address: string;
        inventoryLocation: string;
        pickupInstructions: string | null;
        sortOrder: number;
    }>;
    overview(date?: string): Promise<{
        zones: {
            slots: {
                reserved: number;
                remaining: number;
                available: boolean;
                id: string;
                idempotencyKey: string;
                createdBy: string;
                createdAt: Date;
                updatedAt: Date;
                active: boolean;
                zoneId: string;
                startsAt: Date;
                endsAt: Date;
                capacity: number;
            }[];
            id: string;
            name: string;
            code: string;
            idempotencyKey: string;
            createdBy: string;
            createdAt: Date;
            updatedAt: Date;
            active: boolean;
            fee: number;
            etaMinMinutes: number;
            etaMaxMinutes: number;
        }[];
        couriers: {
            id: string;
            username: string;
            role: import(".prisma/client").$Enums.Role;
        }[];
        pendingOrders: ({
            customer: {
                name: string;
                phone: string;
            };
            deliveryZone: {
                id: string;
                name: string;
                code: string;
                idempotencyKey: string;
                createdBy: string;
                createdAt: Date;
                updatedAt: Date;
                active: boolean;
                fee: number;
                etaMinMinutes: number;
                etaMaxMinutes: number;
            } | null;
            payments: {
                amount: number;
                status: import(".prisma/client").$Enums.PaymentStatus;
            }[];
            logisticsSlot: {
                id: string;
                idempotencyKey: string;
                createdBy: string;
                createdAt: Date;
                updatedAt: Date;
                active: boolean;
                zoneId: string;
                startsAt: Date;
                endsAt: Date;
                capacity: number;
            } | null;
            items: {
                id: string;
                taxCode: string;
                taxRateBps: number;
                taxAmount: number;
                orderId: string;
                unitCost: number;
                productId: string | null;
                imei: string | null;
                sku: string;
                price: number;
                taxBaseAmount: number;
                qty: number;
                lineNumber: number;
                discountAmount: number;
                supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
                supplierIdSnapshot: string | null;
                supplyLeadDaysSnapshot: number | null;
                promisedDate: Date | null;
                fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
                readyAt: Date | null;
                handedOverAt: Date | null;
                inventorySnapshot: Prisma.JsonValue | null;
            }[];
        } & {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        })[];
        runs: ({
            orders: ({
                customer: {
                    name: string;
                    phone: string;
                };
                logisticsSlot: {
                    id: string;
                    idempotencyKey: string;
                    createdBy: string;
                    createdAt: Date;
                    updatedAt: Date;
                    active: boolean;
                    zoneId: string;
                    startsAt: Date;
                    endsAt: Date;
                    capacity: number;
                } | null;
            } & {
                deliverySlot: string | null;
                id: string;
                idempotencyKey: string | null;
                taxAmount: number;
                status: import(".prisma/client").$Enums.OrderStatus;
                createdAt: Date;
                customerId: string;
                storePointId: string | null;
                channel: string;
                isDemo: boolean;
                fulfillmentType: string;
                paymentMode: string;
                paymentModeExplicit: boolean;
                idempotencyRequestHash: string | null;
                storePointCode: string | null;
                storePointName: string | null;
                storePointAddress: string | null;
                posShiftId: string | null;
                pickupPoint: string | null;
                pickupAddress: string | null;
                fulfillmentLocation: string | null;
                deliveryAddress: string | null;
                deliveryZoneId: string | null;
                deliverySlotId: string | null;
                courierId: string | null;
                courierRunId: string | null;
                pickupCode: string | null;
                subtotal: number;
                deliveryFee: number;
                promoCode: string | null;
                promoDiscount: number;
                loyaltyRedeemed: number;
                loyaltyEarned: number;
                taxBaseAmount: number;
                total: number;
                piiConsentAt: Date | null;
            })[];
        } & {
            id: string;
            createdAt: Date;
            courierId: string;
            handedOverAt: Date | null;
            codTotal: number;
            handedOver: boolean;
            collectedTotal: number;
            assignmentIdempotencyKey: string | null;
            handoverIdempotencyKey: string | null;
            handoverAmount: number | null;
            handoverReason: string | null;
        })[];
        pickupPoints: {
            type: string;
            waiting: number;
            status: string;
            id: string;
            name: string;
            code: string;
            idempotencyKey: string;
            createdBy: string;
            createdAt: Date;
            updatedAt: Date;
            active: boolean;
            hours: string;
            address: string;
            inventoryLocation: string;
            pickupInstructions: string | null;
            sortOrder: number;
        }[];
    }>;
    createStorePoint(dto: CreateStorePointDto, actor: string, rawKey?: string): Promise<{
        id: string;
        name: string;
        code: string;
        idempotencyKey: string;
        createdBy: string;
        createdAt: Date;
        updatedAt: Date;
        active: boolean;
        hours: string;
        address: string;
        inventoryLocation: string;
        pickupInstructions: string | null;
        sortOrder: number;
    }>;
    updateStorePoint(id: string, dto: UpdateStorePointDto, actor: string, rawKey?: string): Promise<Prisma.InputJsonValue | null>;
    createZone(dto: CreateDeliveryZoneDto, actor: string, rawKey?: string): Promise<{
        id: string;
        name: string;
        code: string;
        idempotencyKey: string;
        createdBy: string;
        createdAt: Date;
        updatedAt: Date;
        active: boolean;
        fee: number;
        etaMinMinutes: number;
        etaMaxMinutes: number;
    }>;
    createSlot(dto: CreateDeliverySlotDto, actor: string, rawKey?: string): Promise<{
        id: string;
        idempotencyKey: string;
        createdBy: string;
        createdAt: Date;
        updatedAt: Date;
        active: boolean;
        zoneId: string;
        startsAt: Date;
        endsAt: Date;
        capacity: number;
    }>;
}
