import { SupportService } from './support.service';
import { EscalateTicketDto, OpenMineTicketDto, OpenTicketDto, TicketTransitionDto } from './support.dto';
import { AuthPrincipal } from '../auth/jwt.strategy';
import { AuthzService } from '../authz/authz.service';
import { StaffAuthService } from '../staff-auth/staff-auth.service';
export declare class SupportController {
    private readonly support;
    private readonly staffAuth;
    private readonly authz;
    constructor(support: SupportService, staffAuth: StaffAuthService, authz: AuthzService);
    openMine(user: AuthPrincipal, idempotencyKey: string | undefined, dto: OpenMineTicketDto): Promise<{
        id: string;
        idempotencyKey: string | null;
        status: import(".prisma/client").$Enums.TicketStatus;
        createdAt: Date;
        subject: string;
        customerId: string;
        channel: string;
        body: string | null;
        priority: string;
        assignee: string | null;
        sla: Date;
        revision: number;
    }>;
    mine(user: AuthPrincipal, status?: string): import(".prisma/client").Prisma.PrismaPromise<{
        id: string;
        idempotencyKey: string | null;
        status: import(".prisma/client").$Enums.TicketStatus;
        createdAt: Date;
        subject: string;
        customerId: string;
        channel: string;
        body: string | null;
        priority: string;
        assignee: string | null;
        sla: Date;
        revision: number;
    }[]>;
    open(dto: OpenTicketDto, user?: AuthPrincipal, capability?: string): Promise<{
        id: string;
        idempotencyKey: string | null;
        status: import(".prisma/client").$Enums.TicketStatus;
        createdAt: Date;
        subject: string;
        customerId: string;
        channel: string;
        body: string | null;
        priority: string;
        assignee: string | null;
        sla: Date;
        revision: number;
    }>;
    list(user: AuthPrincipal | undefined, customerId?: string, status?: string): Promise<{
        id: string;
        idempotencyKey: string | null;
        status: import(".prisma/client").$Enums.TicketStatus;
        createdAt: Date;
        subject: string;
        customerId: string;
        channel: string;
        body: string | null;
        priority: string;
        assignee: string | null;
        sla: Date;
        revision: number;
    }[]>;
    transition(user: AuthPrincipal, id: string, dto: TicketTransitionDto): Promise<{
        id: string;
        idempotencyKey: string | null;
        status: import(".prisma/client").$Enums.TicketStatus;
        createdAt: Date;
        subject: string;
        customerId: string;
        channel: string;
        body: string | null;
        priority: string;
        assignee: string | null;
        sla: Date;
        revision: number;
    }>;
    escalate(user: AuthPrincipal, id: string, _dto: EscalateTicketDto): Promise<{
        id: string;
        idempotencyKey: string | null;
        status: import(".prisma/client").$Enums.TicketStatus;
        createdAt: Date;
        subject: string;
        customerId: string;
        channel: string;
        body: string | null;
        priority: string;
        assignee: string | null;
        sla: Date;
        revision: number;
    }>;
    private requireStaffPermission;
}
