import { AuditService } from '../audit/audit.service';
import { OutboxService } from '../outbox/outbox.service';
import { GatewayRefundWebhookPayload, PaymentGatewayProvider } from '../payments/payment-gateway-provider';
import { PrismaService } from '../prisma/prisma.service';
import { ResolveRefundDto } from './refunds.dto';
export declare class RefundProcessor {
    private readonly prisma;
    private readonly audit;
    private readonly gateway;
    private readonly outbox?;
    private readonly logger;
    constructor(prisma: PrismaService, audit: AuditService, gateway: PaymentGatewayProvider, outbox?: OutboxService | undefined);
    processRefund(refundId: string, actor?: string, payer?: {
        shiftId: string;
    }): Promise<void>;
    processPending(limit?: number): Promise<number>;
    private processAllocation;
    sweepStaleProviderPending(staleMs?: number, limit?: number, actor?: string): Promise<number>;
    private markProviderPendingStale;
    reconcileProviderRefund(payload: GatewayRefundWebhookPayload, actor: string): Promise<void>;
    resolveRefund(refundId: string, dto: ResolveRefundDto, actor: string, idempotencyKey: string): Promise<{
        id: string;
        idempotencyKey: string;
        orderId: string;
        amount: number;
        status: import(".prisma/client").$Enums.RefundStatus;
        createdAt: Date;
        updatedAt: Date;
        returnId: string | null;
        purpose: import(".prisma/client").$Enums.RefundPurpose;
        reason: string;
        approvalId: string | null;
        approvedAt: Date | null;
        completedAt: Date | null;
        requestHash: string;
        requester: string;
        approver: string | null;
    }>;
    private resolveConfirm;
    private resolveCancel;
    private assertTenderCapacity;
    private finalize;
    private completeRefundOnTx;
    private completeIfReady;
    private reassignCashAllocations;
    private assertExecutionShift;
    private preflightAllocations;
    private markProviderPending;
    private projectRefundFailedOnTx;
    private notifyRefundFailedOnTx;
    private recordFailure;
    private deferPreflightFailure;
}
