import { OrdersService } from './orders.service';
import { CreateMyOrderDto, CreateOrderDto, TransitionDto } from './orders.dto';
import type { AuthPrincipal } from '../auth/jwt.strategy';
import { StaffAuthService } from '../staff-auth/staff-auth.service';
import { AuthzService } from '../authz/authz.service';
import { ReceiptsService } from '../receipts/receipts.service';
import { OrderCancellationsService } from './order-cancellations.service';
import { CreateOrderCancellationDto } from './order-cancellations.dto';
import { OrderCancellationResolutionService } from './order-cancellation-resolution.service';
import { ResolveOrderCancellationDto } from './order-cancellation-resolution.dto';
import { OrderItemHandoverService } from './order-item-handover.service';
import { OrderItemReservationService } from './order-item-reservation.service';
export declare class OrdersController {
    private readonly orders;
    private readonly staffAuth;
    private readonly authz;
    private readonly receipts;
    private readonly cancellations;
    private readonly cancellationResolutions;
    private readonly itemHandovers;
    private readonly itemReservations;
    constructor(orders: OrdersService, staffAuth: StaffAuthService, authz: AuthzService, receipts: ReceiptsService, cancellations: OrderCancellationsService, cancellationResolutions: OrderCancellationResolutionService, itemHandovers: OrderItemHandoverService, itemReservations: OrderItemReservationService);
    reserveItem(user: AuthPrincipal, id: string, itemId: string, key: string | undefined): Promise<unknown>;
    readyItem(user: AuthPrincipal, id: string, itemId: string, key: string | undefined): Promise<unknown>;
    handOverItem(user: AuthPrincipal, id: string, itemId: string, idempotencyKey: string | undefined): Promise<{
        orderId: string;
        orderItemId: string;
        fulfillmentStatus: "handed_over";
        handedOverAt: string;
        orderStatus: string;
        accountingEntryId: string;
    }>;
    mine(user: AuthPrincipal): import(".prisma/client").Prisma.PrismaPromise<{
        deliverySlot: string | null;
        id: string;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        payments: {
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            createdAt: Date;
        }[];
        channel: string;
        fulfillmentType: string;
        pickupPoint: string | null;
        deliveryAddress: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        total: number;
        items: {
            orderLineSupply: {
                status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
                expectedAt: Date | null;
                receivedQty: number;
                orderedQty: number;
            } | null;
            id: string;
            imei: string | null;
            sku: string;
            price: number;
            qty: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
        }[];
        receivables: {
            id: string;
            amount: number;
            status: import(".prisma/client").$Enums.OrderReceivableStatus;
            kind: import(".prisma/client").$Enums.OrderReceivableKind;
            orderItemId: string | null;
            settledAmount: number;
            dueAt: Date | null;
        }[];
    }[]>;
    cancellationPreview(user: AuthPrincipal, id: string): Promise<{
        requestEnabled: boolean;
        automaticRefundEnabled: boolean;
        orderId: string;
        canCancel: boolean;
        blockedReason: string | null;
        policy: string;
        purchaseOrderSent: boolean;
        depositPaid: number;
        estimatedRefundAmount: number;
        supplierExpenseDeduction: number;
        ownerReviewRequired: boolean;
        note: string;
    }>;
    requestCancellation(user: AuthPrincipal, id: string, idempotencyKey: string | undefined, dto: CreateOrderCancellationDto): Promise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.OrderCancellationStatus;
        createdAt: Date;
        completedAt: Date | null;
        refundId: string | null;
        policySnapshot: import(".prisma/client").$Enums.OrderCancellationPolicy;
        purchaseOrderSentSnapshot: boolean;
        depositPaidSnapshot: number;
        requestedRefundAmount: number;
        approvedRefundAmount: number | null;
        customerReason: string;
        ownerReason: string | null;
        resolvedAt: Date | null;
    }>;
    currentCancellation(user: AuthPrincipal, id: string): Promise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.OrderCancellationStatus;
        createdAt: Date;
        completedAt: Date | null;
        refundId: string | null;
        policySnapshot: import(".prisma/client").$Enums.OrderCancellationPolicy;
        purchaseOrderSentSnapshot: boolean;
        depositPaidSnapshot: number;
        requestedRefundAmount: number;
        approvedRefundAmount: number | null;
        customerReason: string;
        ownerReason: string | null;
        resolvedAt: Date | null;
    } | null>;
    cancellationOwnerPreview(user: AuthPrincipal, id: string, cancellationId: string): Promise<{
        canResolve: boolean;
        fullRefundAmount: number;
        partialRefundRules: {
            faultParty: string;
            evidenceRequired: boolean;
            formula: string;
        };
        order: {
            purchaseOrders: {
                id: string;
                status: import(".prisma/client").$Enums.PurchaseOrderStatus;
                sentAt: Date | null;
            }[];
        };
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.OrderCancellationStatus;
        createdAt: Date;
        completedAt: Date | null;
        refundId: string | null;
        evidence: import("@prisma/client/runtime/library").JsonValue;
        policySnapshot: import(".prisma/client").$Enums.OrderCancellationPolicy;
        purchaseOrderSentSnapshot: boolean;
        depositPaidSnapshot: number;
        requestedRefundAmount: number;
        approvedRefundAmount: number | null;
        supplierExpenseAmount: number;
        faultParty: import(".prisma/client").$Enums.OrderCancellationFaultParty | null;
        customerReason: string;
        ownerReason: string | null;
        resolutionAction: import(".prisma/client").$Enums.OrderCancellationResolutionAction | null;
        resolvedBy: string | null;
        resolvedAt: Date | null;
    }>;
    resolveCancellationAsOwner(user: AuthPrincipal, id: string, cancellationId: string, idempotencyKey: string | undefined, dto: ResolveOrderCancellationDto): Promise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.OrderCancellationStatus;
        createdAt: Date;
        completedAt: Date | null;
        refundId: string | null;
        evidence: import("@prisma/client/runtime/library").JsonValue;
        policySnapshot: import(".prisma/client").$Enums.OrderCancellationPolicy;
        purchaseOrderSentSnapshot: boolean;
        depositPaidSnapshot: number;
        requestedRefundAmount: number;
        approvedRefundAmount: number | null;
        supplierExpenseAmount: number;
        faultParty: import(".prisma/client").$Enums.OrderCancellationFaultParty | null;
        customerReason: string;
        ownerReason: string | null;
        resolutionAction: import(".prisma/client").$Enums.OrderCancellationResolutionAction | null;
        resolvedBy: string | null;
        resolvedAt: Date | null;
    }>;
    createMine(user: AuthPrincipal, idempotencyKey: string | undefined, dto: CreateMyOrderDto): Promise<{
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
    } & {
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    } & {
        paymentSchedule: import(".prisma/client").OrderReceivable[];
        initialDue: number;
        balanceDue: number;
    }>;
    queue(user: AuthPrincipal, status?: string): Promise<({
        customer: {
            name: string;
            phone: string;
        };
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
    } & {
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    })[]>;
    ledger(user: AuthPrincipal, id: string): Promise<{
        actor: string | null;
        id: string;
        type: string;
        ts: Date;
    }[]>;
    get(user: AuthPrincipal, id: string): Promise<{
        deliverySlot: string | null;
        id: string;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        payments: {
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            createdAt: Date;
        }[];
        channel: string;
        fulfillmentType: string;
        pickupPoint: string | null;
        deliveryAddress: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        total: number;
        items: {
            orderLineSupply: {
                status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
                expectedAt: Date | null;
                receivedQty: number;
                orderedQty: number;
            } | null;
            id: string;
            imei: string | null;
            sku: string;
            price: number;
            qty: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
        }[];
        receivables: {
            id: string;
            amount: number;
            status: import(".prisma/client").$Enums.OrderReceivableStatus;
            kind: import(".prisma/client").$Enums.OrderReceivableKind;
            orderItemId: string | null;
            settledAmount: number;
            dueAt: Date | null;
        }[];
    } | ({
        payments: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        }[];
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
    } & {
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    })>;
    customerReceipt(user: AuthPrincipal, id: string): Promise<{
        markup: string;
    }>;
    guestOrder(capability: string | undefined, id: string): Promise<{
        order: {
            deliverySlot: string | null;
            id: string;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            payments: {
                amount: number;
                method: import(".prisma/client").$Enums.PaymentMethod;
                status: import(".prisma/client").$Enums.PaymentStatus;
                createdAt: Date;
            }[];
            channel: string;
            fulfillmentType: string;
            pickupPoint: string | null;
            deliveryAddress: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            total: number;
            items: {
                orderLineSupply: {
                    status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
                    expectedAt: Date | null;
                    receivedQty: number;
                    orderedQty: number;
                } | null;
                id: string;
                imei: string | null;
                sku: string;
                price: number;
                qty: number;
                discountAmount: number;
                supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
                supplyLeadDaysSnapshot: number | null;
                promisedDate: Date | null;
                fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
                readyAt: Date | null;
                handedOverAt: Date | null;
            }[];
            receivables: {
                id: string;
                amount: number;
                status: import(".prisma/client").$Enums.OrderReceivableStatus;
                kind: import(".prisma/client").$Enums.OrderReceivableKind;
                orderItemId: string | null;
                settledAmount: number;
                dueAt: Date | null;
            }[];
        };
        timeline: {
            type: string;
            ts: Date;
        }[];
    }>;
    guestReceipt(capability: string | undefined, id: string): Promise<{
        markup: string;
    }>;
    create(capability: string | undefined, idempotencyKey: string | undefined, dto: CreateOrderDto): Promise<{
        guestAccess: {
            capability: string;
            expiresIn: number;
        };
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
        paymentSchedule: import(".prisma/client").OrderReceivable[];
        initialDue: number;
        balanceDue: number;
    }>;
    reserve(user: AuthPrincipal, id: string): Promise<{
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    }>;
    fulfill(user: AuthPrincipal, id: string): Promise<{
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        };
        assigned: string[];
    }>;
    transition(user: AuthPrincipal, id: string, dto: TransitionDto): Promise<{
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    }>;
}
