import { Prisma } from '@prisma/client';
import { AuditInput } from '../audit/audit.service';
import { UnitsService } from '../units/units.service';
export declare function handOverReadyOrderItemOnTx(tx: Prisma.TransactionClient, input: {
    orderId: string;
    orderItemId: string;
    paymentMode: string;
    actor: string;
    units: UnitsService;
    events: AuditInput[];
    occurredAt?: Date;
}): Promise<{
    item: {
        id: string;
        taxCode: string;
        taxRateBps: number;
        taxAmount: number;
        orderId: string;
        unitCost: number;
        productId: string | null;
        imei: string | null;
        sku: string;
        price: number;
        taxBaseAmount: number;
        qty: number;
        lineNumber: number;
        discountAmount: number;
        supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
        supplierIdSnapshot: string | null;
        supplyLeadDaysSnapshot: number | null;
        promisedDate: Date | null;
        fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
        readyAt: Date | null;
        handedOverAt: Date | null;
        inventorySnapshot: Prisma.JsonValue | null;
    };
    accountingEntry: {
        idempotent: boolean;
        id: string;
        idempotencyKey: string;
        sourceType: string;
        sourceRef: string;
        description: string;
        point: string | null;
        currency: string;
        documentAmount: number | null;
        exchangeRateMicros: number;
        baseAmount: number | null;
        taxCode: string;
        taxRateBps: number;
        taxAmount: number;
        occurredAt: Date;
        postedAt: Date;
        createdBy: string;
        reversalOfId: string | null;
        lines: Array<{
            accountCode: string;
            debit: number;
            credit: number;
            memo: string | null;
        }>;
    };
    liability: number;
    codReceivable: number;
}>;
