import { ConfigService } from '@nestjs/config';
import { OrderReceivable, OrderStatus, Prisma, StorePoint } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { SettingsService } from '../settings/settings.service';
import { AuditService } from '../audit/audit.service';
import { UnitsService } from '../units/units.service';
import { CreateOrderDto } from './orders.dto';
import { OutboxService } from '../outbox/outbox.service';
import { LogisticsService } from '../logistics/logistics.service';
import { PromotionLine, PromotionsService } from '../promotions/promotions.service';
import { CampaignAttributionService } from '../campaigns/campaign-attribution.service';
import { type OrderInventorySnapshot } from '../inventory/order-inventory-sale';
interface CanonicalPricing {
    subtotal: number;
    deliveryFee: number;
    promoCode: string | null;
    promoDiscount: number;
    loyaltyPoints: number;
    promotionLines?: PromotionLine[];
    unitCosts?: Record<string, number>;
    unitCostsByLine?: number[];
    posShiftId?: string;
    inventorySnapshots?: Record<string, OrderInventorySnapshot>;
    hasToOrderLine?: boolean;
    linePolicies?: Record<string, {
        productId: string;
        supplyMode: 'own_stock' | 'to_order';
        supplierId: string | null;
        supplyLeadDays: number | null;
        supplierOfferId: string | null;
    }>;
}
type OrderWithItems = Prisma.OrderGetPayload<{
    include: {
        items: true;
    };
}>;
type CommerceOrderResult = OrderWithItems & {
    paymentSchedule: OrderReceivable[];
    initialDue: number;
    balanceDue: number;
};
export declare class OrdersService {
    private readonly prisma;
    private readonly audit;
    private readonly units;
    private readonly outbox?;
    private readonly config?;
    private readonly logistics?;
    private readonly promotions?;
    private readonly campaignAttribution?;
    private readonly settings?;
    constructor(prisma: PrismaService, audit: AuditService, units: UnitsService, outbox?: OutboxService | undefined, config?: ConfigService | undefined, logistics?: LogisticsService | undefined, promotions?: PromotionsService | undefined, campaignAttribution?: CampaignAttributionService | undefined, settings?: SettingsService | undefined);
    get(id: string): Prisma.Prisma__OrderClient<({
        payments: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        }[];
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: Prisma.JsonValue | null;
        }[];
    } & {
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    }) | null, null, import("@prisma/client/runtime/library").DefaultArgs>;
    getForStaff(id: string, staffId: string): Promise<({
        payments: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        }[];
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: Prisma.JsonValue | null;
        }[];
    } & {
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    }) | {
        posShiftId: null;
        payments: never[];
        drawerBlind: boolean;
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: Prisma.JsonValue | null;
        }[];
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    } | null>;
    isOwnOpenShiftOrder(orderId: string, staffId: string): Promise<boolean>;
    getGuest(id: string): Prisma.Prisma__OrderClient<{
        deliverySlot: string | null;
        id: string;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        payments: {
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            createdAt: Date;
        }[];
        customerId: string;
        channel: string;
        fulfillmentType: string;
        pickupPoint: string | null;
        deliveryAddress: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        total: number;
        items: {
            orderLineSupply: {
                status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
                expectedAt: Date | null;
                receivedQty: number;
                orderedQty: number;
            } | null;
            id: string;
            imei: string | null;
            sku: string;
            price: number;
            qty: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
        }[];
        receivables: {
            id: string;
            amount: number;
            status: import(".prisma/client").$Enums.OrderReceivableStatus;
            kind: import(".prisma/client").$Enums.OrderReceivableKind;
            orderItemId: string | null;
            settledAmount: number;
            dueAt: Date | null;
        }[];
    } | null, null, import("@prisma/client/runtime/library").DefaultArgs>;
    getForCustomer(id: string, customerId: string): Prisma.Prisma__OrderClient<{
        deliverySlot: string | null;
        id: string;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        payments: {
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            createdAt: Date;
        }[];
        channel: string;
        fulfillmentType: string;
        pickupPoint: string | null;
        deliveryAddress: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        total: number;
        items: {
            orderLineSupply: {
                status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
                expectedAt: Date | null;
                receivedQty: number;
                orderedQty: number;
            } | null;
            id: string;
            imei: string | null;
            sku: string;
            price: number;
            qty: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
        }[];
        receivables: {
            id: string;
            amount: number;
            status: import(".prisma/client").$Enums.OrderReceivableStatus;
            kind: import(".prisma/client").$Enums.OrderReceivableKind;
            orderItemId: string | null;
            settledAmount: number;
            dueAt: Date | null;
        }[];
    } | null, null, import("@prisma/client/runtime/library").DefaultArgs>;
    listByCustomer(customerId: string): Prisma.PrismaPromise<{
        deliverySlot: string | null;
        id: string;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        payments: {
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            createdAt: Date;
        }[];
        channel: string;
        fulfillmentType: string;
        pickupPoint: string | null;
        deliveryAddress: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        total: number;
        items: {
            orderLineSupply: {
                status: import(".prisma/client").$Enums.OrderLineSupplyStatus;
                expectedAt: Date | null;
                receivedQty: number;
                orderedQty: number;
            } | null;
            id: string;
            imei: string | null;
            sku: string;
            price: number;
            qty: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
        }[];
        receivables: {
            id: string;
            amount: number;
            status: import(".prisma/client").$Enums.OrderReceivableStatus;
            kind: import(".prisma/client").$Enums.OrderReceivableKind;
            orderItemId: string | null;
            settledAmount: number;
            dueAt: Date | null;
        }[];
    }[]>;
    ledger(orderId: string): Prisma.PrismaPromise<{
        id: string;
        type: string;
        actor: string;
        ts: Date;
        payload: Prisma.JsonValue;
        refs: string[];
    }[]>;
    customerLedger(orderId: string): Promise<{
        actor: string | null;
        id: string;
        type: string;
        ts: Date;
    }[]>;
    sweepNoShow(options?: {
        now?: Date;
        limit?: number;
    }, actor?: string): Promise<{
        reminders: number;
        ownerTasks: number;
    }>;
    createFromCatalog(dto: CreateOrderDto, actor: string, idempotencyKey?: string, allowLoyalty?: boolean): Promise<CommerceOrderResult>;
    create(dto: CreateOrderDto, actor: string, idempotencyKey?: string, pricing?: CanonicalPricing, storePoint?: StorePoint, requestHash?: string): Promise<CommerceOrderResult>;
    private deliverySelection;
    private requirePromotions;
    private orderLineSupplyMap;
    reserve(orderId: string, actor: string): Promise<{
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    }>;
    transition(orderId: string, to: OrderStatus, actor: string): Promise<{
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    }>;
    listByStatus(status: OrderStatus, limit?: number): Prisma.PrismaPromise<({
        customer: {
            name: string;
            phone: string;
        };
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: Prisma.JsonValue | null;
        }[];
    } & {
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    })[]>;
    listByStatusForStaff(status: OrderStatus, staffId: string, limit?: number): Promise<({
        customer: {
            name: string;
            phone: string;
        };
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: Prisma.JsonValue | null;
        }[];
    } & {
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    })[]>;
    fulfill(orderId: string, actor: string): Promise<{
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        };
        assigned: string[];
    }>;
    private assertNotDemo;
    private reserveQuantityOnTx;
    private resolveStorePointFromDatabase;
}
export {};
