"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.RegisterPushTokenDto = exports.PUSH_SCOPES = exports.PUSH_PLATFORMS = exports.PUSH_TOKEN_PATTERN = exports.FCM_TOKEN_PATTERN = void 0;
const swagger_1 = require("@nestjs/swagger");
const class_validator_1 = require("class-validator");
exports.FCM_TOKEN_PATTERN = /^(?=.{20,4096}$)[A-Za-z0-9_:-]+$/;
exports.PUSH_TOKEN_PATTERN = /^(?:(ExponentPushToken|ExpoPushToken)\[[A-Za-z0-9_-]+\]|[a-fA-F0-9]{64,200}|(?=.{20,4096}$)[A-Za-z0-9_:-]+)$/;
exports.PUSH_PLATFORMS = ['ios', 'android', 'web', 'unknown'];
exports.PUSH_SCOPES = ['anonymous', 'customer', 'staff'];
class RegisterPushTokenDto {
}
exports.RegisterPushTokenDto = RegisterPushTokenDto;
__decorate([
    (0, swagger_1.ApiProperty)({
        example: 'ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]',
        description: 'Expo, native APNs or FCM registration token.',
    }),
    (0, class_validator_1.IsString)(),
    (0, class_validator_1.MaxLength)(4096),
    (0, class_validator_1.Matches)(exports.PUSH_TOKEN_PATTERN, { message: 'token must be an Expo, APNs or FCM push token' }),
    __metadata("design:type", String)
], RegisterPushTokenDto.prototype, "token", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({ enum: exports.PUSH_PLATFORMS, example: 'ios' }),
    (0, class_validator_1.IsIn)(exports.PUSH_PLATFORMS),
    __metadata("design:type", String)
], RegisterPushTokenDto.prototype, "platform", void 0);
__decorate([
    (0, swagger_1.ApiProperty)({
        example: 'ios-iphone-15-pro:8F4C5B2E',
        description: 'Stable local installation/device key generated by the native app.',
    }),
    (0, class_validator_1.IsString)(),
    (0, class_validator_1.MaxLength)(160),
    __metadata("design:type", String)
], RegisterPushTokenDto.prototype, "deviceId", void 0);
__decorate([
    (0, swagger_1.ApiPropertyOptional)({
        enum: exports.PUSH_SCOPES,
        example: 'customer',
        description: 'Client-requested scope; authenticated JWT wins over this value.',
    }),
    (0, class_validator_1.IsOptional)(),
    (0, class_validator_1.IsIn)(exports.PUSH_SCOPES),
    __metadata("design:type", String)
], RegisterPushTokenDto.prototype, "scope", void 0);
//# sourceMappingURL=push-token.dto.js.map