import { PaymentsService } from './payments.service';
import { PayDto, RefundDto, SettleOrderReceivableDto, VoidPaymentDto } from './payments.dto';
import { PaymentIntentsService } from './payment-intents.service';
import { CreatePaymentIntentDto, PaymentWebhookDto } from './payment-intents.dto';
import { ConfigService } from '@nestjs/config';
import { PaymentGatewayProvider } from './payment-gateway-provider';
import { AuthPrincipal } from '../auth/jwt.strategy';
import { StaffAuthService } from '../staff-auth/staff-auth.service';
import { RefundsService } from '../refunds/refunds.service';
export declare class PaymentsController {
    private readonly payments;
    private readonly intents;
    private readonly staffAuth;
    private readonly config;
    private readonly gateway;
    private readonly refunds?;
    constructor(payments: PaymentsService, intents: PaymentIntentsService, staffAuth: StaffAuthService, config: ConfigService, gateway: PaymentGatewayProvider, refunds?: RefundsService | undefined);
    paymentMethods(): import("./payment-methods-availability").CustomerPaymentMethods;
    find(user: AuthPrincipal, orderId?: string, shiftId?: string): Promise<{
        id: string;
        idempotencyKey: string | null;
        point: string | null;
        accountCode: string | null;
        accountingEntryId: string | null;
        txnId: string | null;
        orderId: string | null;
        serviceWorkOrderId: string | null;
        originalPaymentId: string | null;
        giftCardId: string | null;
        amount: number;
        method: import(".prisma/client").$Enums.PaymentMethod;
        status: import(".prisma/client").$Enums.PaymentStatus;
        shiftId: string | null;
        receivedBy: string | null;
        createdAt: Date;
    }[]>;
    pay(user: AuthPrincipal | undefined, capability: string | undefined, idempotencyKey: string | undefined, dto: PayDto): Promise<{
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        } | null;
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        idempotent: boolean;
    } | {
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        } | null;
        payments: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        }[];
        idempotent: boolean;
    }>;
    settleReceivable(user: AuthPrincipal, receivableId: string, idempotencyKey: string | undefined, dto: SettleOrderReceivableDto): Promise<{
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        allocation: {
            id: string;
            amount: number;
            createdAt: Date;
            paymentId: string;
            receivableId: string;
        };
        idempotent: boolean;
    }>;
    intent(capability: string | undefined, idempotencyKey: string | undefined, dto: CreatePaymentIntentDto): Promise<import("./payment-gateway-provider").PaymentIntentView>;
    customerIntent(user: AuthPrincipal, idempotencyKey: string | undefined, dto: CreatePaymentIntentDto): Promise<import("./payment-gateway-provider").PaymentIntentView>;
    webhook(request: {
        rawBody?: Buffer;
        headers: Record<string, string | string[] | undefined>;
    }, dto: PaymentWebhookDto): Promise<({
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        } | null;
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        idempotent: boolean;
    } | {
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        } | null;
        payments: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        }[];
        idempotent: boolean;
    }) & {
        parked?: boolean;
    }>;
    refund(user: AuthPrincipal, id: string, idempotencyKey: string | undefined, dto: RefundDto): Promise<{
        approvalId: string;
        status: "requested";
    } | ({
        return: ({
            items: {
                id: string;
                createdAt: Date;
                returnId: string;
                qty: number;
                orderItemId: string;
                refundAmount: number;
            }[];
        } & {
            id: string;
            idempotencyKey: string | null;
            orderId: string;
            status: import(".prisma/client").$Enums.ReturnStatus;
            createdAt: Date;
            reason: string;
            refundId: string | null;
            refundAmount: number;
            isFullOrder: boolean;
            restockLocation: string | null;
            restockedAt: Date | null;
        }) | null;
        approval: {
            id: string;
            idempotencyKey: string | null;
            sourceRef: string | null;
            status: import(".prisma/client").$Enums.ApprovalStatus;
            createdAt: Date;
            consumedAt: Date | null;
            reason: string;
            evidence: import("@prisma/client/runtime/library").JsonValue | null;
            requester: string;
            approver: string | null;
            action: string;
        } | null;
        lines: ({
            returnItem: {
                id: string;
                createdAt: Date;
                returnId: string;
                qty: number;
                orderItemId: string;
                refundAmount: number;
            };
        } & {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            createdAt: Date;
            taxBaseAmount: number;
            qty: number;
            refundId: string;
            grossAmount: number;
            revenueAmount: number;
            returnItemId: string;
        })[];
        allocations: ({
            originalPayment: {
                id: string;
                idempotencyKey: string | null;
                point: string | null;
                accountCode: string | null;
                accountingEntryId: string | null;
                txnId: string | null;
                orderId: string | null;
                serviceWorkOrderId: string | null;
                originalPaymentId: string | null;
                giftCardId: string | null;
                amount: number;
                method: import(".prisma/client").$Enums.PaymentMethod;
                status: import(".prisma/client").$Enums.PaymentStatus;
                shiftId: string | null;
                receivedBy: string | null;
                createdAt: Date;
            };
            refundPayment: {
                id: string;
                idempotencyKey: string | null;
                point: string | null;
                accountCode: string | null;
                accountingEntryId: string | null;
                txnId: string | null;
                orderId: string | null;
                serviceWorkOrderId: string | null;
                originalPaymentId: string | null;
                giftCardId: string | null;
                amount: number;
                method: import(".prisma/client").$Enums.PaymentMethod;
                status: import(".prisma/client").$Enums.PaymentStatus;
                shiftId: string | null;
                receivedBy: string | null;
                createdAt: Date;
            } | null;
        } & {
            id: string;
            accountingEntryId: string | null;
            originalPaymentId: string;
            amount: number;
            status: import(".prisma/client").$Enums.RefundAllocationStatus;
            shiftId: string | null;
            createdAt: Date;
            updatedAt: Date;
            attempts: number;
            lastError: string | null;
            nextAttemptAt: Date | null;
            refundId: string;
            ordinal: number;
            methodSnapshot: import(".prisma/client").$Enums.PaymentMethod;
            providerRefundId: string | null;
            lockedAt: Date | null;
            refundPaymentId: string | null;
        })[];
    } & {
        id: string;
        idempotencyKey: string;
        orderId: string;
        amount: number;
        status: import(".prisma/client").$Enums.RefundStatus;
        createdAt: Date;
        updatedAt: Date;
        returnId: string | null;
        purpose: import(".prisma/client").$Enums.RefundPurpose;
        reason: string;
        approvalId: string | null;
        approvedAt: Date | null;
        completedAt: Date | null;
        requestHash: string;
        requester: string;
        approver: string | null;
    }) | null>;
    voidPayment(user: AuthPrincipal, id: string, idempotencyKey: string | undefined, dto: VoidPaymentDto): Promise<{
        id: string;
        idempotencyKey: string | null;
        point: string | null;
        accountCode: string | null;
        accountingEntryId: string | null;
        txnId: string | null;
        orderId: string | null;
        serviceWorkOrderId: string | null;
        originalPaymentId: string | null;
        giftCardId: string | null;
        amount: number;
        method: import(".prisma/client").$Enums.PaymentMethod;
        status: import(".prisma/client").$Enums.PaymentStatus;
        shiftId: string | null;
        receivedBy: string | null;
        createdAt: Date;
    }>;
}
