import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { UnitsService } from '../units/units.service';
import { OrdersService } from '../orders/orders.service';
import { ApprovalsService } from '../approvals/approvals.service';
import { GiftcardsService } from '../giftcards/giftcards.service';
import { PayDto, SettleOrderReceivableDto, VoidPaymentDto } from './payments.dto';
import { CampaignAttributionService } from '../campaigns/campaign-attribution.service';
import { OutboxService } from '../outbox/outbox.service';
interface PaymentTender {
    method: PayDto['method'];
    amount: number;
    txnId?: string;
    idempotencyKey?: string;
    giftCardCode?: string;
}
interface PaymentContext {
    staffId?: string;
    idempotencyKey?: string;
}
export declare class PaymentsService {
    private readonly prisma;
    private readonly audit;
    private readonly units;
    private readonly approvals;
    private readonly giftcards?;
    private readonly orders?;
    private readonly campaignAttribution?;
    private readonly outbox?;
    constructor(prisma: PrismaService, audit: AuditService, units: UnitsService, approvals: ApprovalsService, giftcards?: GiftcardsService | undefined, orders?: OrdersService | undefined, campaignAttribution?: CampaignAttributionService | undefined, outbox?: OutboxService | undefined);
    get(id: string): Prisma.Prisma__PaymentClient<{
        id: string;
        idempotencyKey: string | null;
        point: string | null;
        accountCode: string | null;
        accountingEntryId: string | null;
        txnId: string | null;
        orderId: string | null;
        serviceWorkOrderId: string | null;
        originalPaymentId: string | null;
        giftCardId: string | null;
        amount: number;
        method: import(".prisma/client").$Enums.PaymentMethod;
        status: import(".prisma/client").$Enums.PaymentStatus;
        shiftId: string | null;
        receivedBy: string | null;
        createdAt: Date;
    } | null, null, import("@prisma/client/runtime/library").DefaultArgs>;
    settleReceivable(receivableId: string, dto: SettleOrderReceivableDto, actor: string, context: {
        staffId: string;
        idempotencyKey?: string;
    }): Promise<{
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        allocation: {
            id: string;
            amount: number;
            createdAt: Date;
            paymentId: string;
            receivableId: string;
        };
        idempotent: boolean;
    }>;
    voidPending(paymentId: string, reason: VoidPaymentDto['reason'], actor: string, idempotencyKey: string): Promise<{
        id: string;
        idempotencyKey: string | null;
        point: string | null;
        accountCode: string | null;
        accountingEntryId: string | null;
        txnId: string | null;
        orderId: string | null;
        serviceWorkOrderId: string | null;
        originalPaymentId: string | null;
        giftCardId: string | null;
        amount: number;
        method: import(".prisma/client").$Enums.PaymentMethod;
        status: import(".prisma/client").$Enums.PaymentStatus;
        shiftId: string | null;
        receivedBy: string | null;
        createdAt: Date;
    }>;
    refund(paymentId: string, amount: number, reason: string, requester: string, returnId?: string, settlement?: {
        shiftId?: string;
        externalReference?: string;
        allocations?: Array<{
            paymentId: string;
            amount: number;
            shiftId?: string;
            externalReference?: string;
        }>;
    }): Promise<{
        approvalId: string;
        status: "requested";
    }>;
    findForStaff(staffId: string, where: {
        orderId?: string;
        shiftId?: string;
    }): Promise<{
        id: string;
        idempotencyKey: string | null;
        point: string | null;
        accountCode: string | null;
        accountingEntryId: string | null;
        txnId: string | null;
        orderId: string | null;
        serviceWorkOrderId: string | null;
        originalPaymentId: string | null;
        giftCardId: string | null;
        amount: number;
        method: import(".prisma/client").$Enums.PaymentMethod;
        status: import(".prisma/client").$Enums.PaymentStatus;
        shiftId: string | null;
        receivedBy: string | null;
        createdAt: Date;
    }[]>;
    findByTxnId(txnId: string): Prisma.Prisma__PaymentClient<{
        id: string;
        idempotencyKey: string | null;
        point: string | null;
        accountCode: string | null;
        accountingEntryId: string | null;
        txnId: string | null;
        orderId: string | null;
        serviceWorkOrderId: string | null;
        originalPaymentId: string | null;
        giftCardId: string | null;
        amount: number;
        method: import(".prisma/client").$Enums.PaymentMethod;
        status: import(".prisma/client").$Enums.PaymentStatus;
        shiftId: string | null;
        receivedBy: string | null;
        createdAt: Date;
    } | null, null, import("@prisma/client/runtime/library").DefaultArgs>;
    payForCustomer(customerId: string, dto: PayDto, actor: string): Promise<{
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        } | null;
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        idempotent: boolean;
    } | {
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        } | null;
        payments: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        }[];
        idempotent: boolean;
    }>;
    pay(dto: PayDto, actor: string, context?: PaymentContext): Promise<{
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        } | null;
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        idempotent: boolean;
    } | {
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        } | null;
        payments: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        }[];
        idempotent: boolean;
    }>;
    payMany(dto: {
        orderId: string;
        shiftId?: string;
        payments: PaymentTender[];
    }, actor: string, context?: PaymentContext): Promise<{
        order: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        } | null;
        payment: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        };
        payments: {
            id: string;
            idempotencyKey: string | null;
            point: string | null;
            accountCode: string | null;
            accountingEntryId: string | null;
            txnId: string | null;
            orderId: string | null;
            serviceWorkOrderId: string | null;
            originalPaymentId: string | null;
            giftCardId: string | null;
            amount: number;
            method: import(".prisma/client").$Enums.PaymentMethod;
            status: import(".prisma/client").$Enums.PaymentStatus;
            shiftId: string | null;
            receivedBy: string | null;
            createdAt: Date;
        }[];
        idempotent: boolean;
    }>;
    private normalizeTender;
    private assertPaymentReplay;
    private activateSupplyProcurementOnTx;
    private resolveCashShiftOnTx;
}
export {};
