import { CourierService } from './courier.service';
import { CompleteDeliveryDto, CreateRunDto, HandoverDto, RemoveFromRunDto } from './courier.dto';
import { AuthPrincipal } from '../auth/jwt.strategy';
import { EvidenceService } from '../evidence/evidence.service';
export declare class CourierController {
    private readonly courier;
    private readonly evidence;
    constructor(courier: CourierService, evidence: EvidenceService);
    getRun(user: AuthPrincipal, id: string): Promise<{
        orders: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        courierId: string;
        handedOverAt: Date | null;
        codTotal: number;
        handedOver: boolean;
        collectedTotal: number;
        assignmentIdempotencyKey: string | null;
        handoverIdempotencyKey: string | null;
        handoverAmount: number | null;
        handoverReason: string | null;
    }>;
    createRun(user: AuthPrincipal, key: string | undefined, dto: CreateRunDto): Promise<{
        orderIds: string[];
        id: string;
        createdAt: Date;
        courierId: string;
        handedOverAt: Date | null;
        codTotal: number;
        handedOver: boolean;
        collectedTotal: number;
        assignmentIdempotencyKey: string | null;
        handoverIdempotencyKey: string | null;
        handoverAmount: number | null;
        handoverReason: string | null;
    }>;
    listMine(user: AuthPrincipal): import(".prisma/client").Prisma.PrismaPromise<({
        customer: {
            name: string;
            phone: string;
        };
        courierRun: {
            id: string;
            codTotal: number;
            handedOver: boolean;
            collectedTotal: number;
        } | null;
        payments: {
            amount: number;
            status: import(".prisma/client").$Enums.PaymentStatus;
        }[];
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
    } & {
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    })[]>;
    start(user: AuthPrincipal, id: string, key?: string): Promise<{
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    }>;
    deliver(user: AuthPrincipal, id: string, key: string | undefined, dto: CompleteDeliveryDto): Promise<{
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    }>;
    removeFromRun(user: AuthPrincipal, id: string, key: string | undefined, dto: RemoveFromRunDto): Promise<{
        orderId: string;
        runId: string;
        status: "paid";
        codReleased: number;
        codTotal: number;
        collectedTotal: number;
    }>;
    handover(user: AuthPrincipal, key: string | undefined, dto: HandoverDto): Promise<{
        id: string;
        createdAt: Date;
        courierId: string;
        handedOverAt: Date | null;
        codTotal: number;
        handedOver: boolean;
        collectedTotal: number;
        assignmentIdempotencyKey: string | null;
        handoverIdempotencyKey: string | null;
        handoverAmount: number | null;
        handoverReason: string | null;
    } & {
        diff: number;
    }>;
}
