import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { CompleteDeliveryDto, CreateRunDto, FailDeliveryDto, HandoverDto, RemoveFromRunDto } from './courier.dto';
import { OutboxService } from '../outbox/outbox.service';
import { UnitsService } from '../units/units.service';
export declare class CourierService {
    private readonly prisma;
    private readonly audit;
    private readonly outbox;
    private readonly units;
    constructor(prisma: PrismaService, audit: AuditService, outbox: OutboxService, units: UnitsService);
    listMine(courierId: string): Prisma.PrismaPromise<({
        customer: {
            name: string;
            phone: string;
        };
        courierRun: {
            id: string;
            codTotal: number;
            handedOver: boolean;
            collectedTotal: number;
        } | null;
        payments: {
            amount: number;
            status: import(".prisma/client").$Enums.PaymentStatus;
        }[];
        items: {
            id: string;
            taxCode: string;
            taxRateBps: number;
            taxAmount: number;
            orderId: string;
            unitCost: number;
            productId: string | null;
            imei: string | null;
            sku: string;
            price: number;
            taxBaseAmount: number;
            qty: number;
            lineNumber: number;
            discountAmount: number;
            supplyModeSnapshot: import(".prisma/client").$Enums.SupplyMode;
            supplierIdSnapshot: string | null;
            supplyLeadDaysSnapshot: number | null;
            promisedDate: Date | null;
            fulfillmentStatus: import(".prisma/client").$Enums.OrderLineFulfillmentStatus;
            readyAt: Date | null;
            handedOverAt: Date | null;
            inventorySnapshot: Prisma.JsonValue | null;
        }[];
    } & {
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    })[]>;
    assertAssignedCourier(orderId: string, courierId: string): Promise<void>;
    getRun(id: string, expectedCourierId?: string): Promise<({
        orders: {
            deliverySlot: string | null;
            id: string;
            idempotencyKey: string | null;
            taxAmount: number;
            status: import(".prisma/client").$Enums.OrderStatus;
            createdAt: Date;
            customerId: string;
            storePointId: string | null;
            channel: string;
            isDemo: boolean;
            fulfillmentType: string;
            paymentMode: string;
            paymentModeExplicit: boolean;
            idempotencyRequestHash: string | null;
            storePointCode: string | null;
            storePointName: string | null;
            storePointAddress: string | null;
            posShiftId: string | null;
            pickupPoint: string | null;
            pickupAddress: string | null;
            fulfillmentLocation: string | null;
            deliveryAddress: string | null;
            deliveryZoneId: string | null;
            deliverySlotId: string | null;
            courierId: string | null;
            courierRunId: string | null;
            pickupCode: string | null;
            subtotal: number;
            deliveryFee: number;
            promoCode: string | null;
            promoDiscount: number;
            loyaltyRedeemed: number;
            loyaltyEarned: number;
            taxBaseAmount: number;
            total: number;
            piiConsentAt: Date | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        courierId: string;
        handedOverAt: Date | null;
        codTotal: number;
        handedOver: boolean;
        collectedTotal: number;
        assignmentIdempotencyKey: string | null;
        handoverIdempotencyKey: string | null;
        handoverAmount: number | null;
        handoverReason: string | null;
    }) | null>;
    createRun(dto: CreateRunDto, actor: string, idempotencyKey: string): Promise<{
        orderIds: string[];
        id: string;
        createdAt: Date;
        courierId: string;
        handedOverAt: Date | null;
        codTotal: number;
        handedOver: boolean;
        collectedTotal: number;
        assignmentIdempotencyKey: string | null;
        handoverIdempotencyKey: string | null;
        handoverAmount: number | null;
        handoverReason: string | null;
    }>;
    startDelivery(orderId: string, courierId: string, idempotencyKey: string): Promise<{
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    }>;
    completeDelivery(orderId: string, dto: CompleteDeliveryDto, courierId: string, idempotencyKey: string): Promise<{
        deliverySlot: string | null;
        id: string;
        idempotencyKey: string | null;
        taxAmount: number;
        status: import(".prisma/client").$Enums.OrderStatus;
        createdAt: Date;
        customerId: string;
        storePointId: string | null;
        channel: string;
        isDemo: boolean;
        fulfillmentType: string;
        paymentMode: string;
        paymentModeExplicit: boolean;
        idempotencyRequestHash: string | null;
        storePointCode: string | null;
        storePointName: string | null;
        storePointAddress: string | null;
        posShiftId: string | null;
        pickupPoint: string | null;
        pickupAddress: string | null;
        fulfillmentLocation: string | null;
        deliveryAddress: string | null;
        deliveryZoneId: string | null;
        deliverySlotId: string | null;
        courierId: string | null;
        courierRunId: string | null;
        pickupCode: string | null;
        subtotal: number;
        deliveryFee: number;
        promoCode: string | null;
        promoDiscount: number;
        loyaltyRedeemed: number;
        loyaltyEarned: number;
        taxBaseAmount: number;
        total: number;
        piiConsentAt: Date | null;
    }>;
    failDelivery(orderId: string, dto: FailDeliveryDto, courierId: string, idempotencyKey: string): Promise<{
        orderId: string;
        recorded: boolean;
        status: "out_for_delivery";
    }>;
    removeOrderFromRun(orderId: string, dto: RemoveFromRunDto, actor: string, expectedCourierId: string | undefined, idempotencyKey: string): Promise<RemoveFromRunResult>;
    handover(dto: HandoverDto, actor: string, expectedCourierId: string | undefined, idempotencyKey: string): Promise<{
        id: string;
        createdAt: Date;
        courierId: string;
        handedOverAt: Date | null;
        codTotal: number;
        handedOver: boolean;
        collectedTotal: number;
        assignmentIdempotencyKey: string | null;
        handoverIdempotencyKey: string | null;
        handoverAmount: number | null;
        handoverReason: string | null;
    } & {
        diff: number;
    }>;
    private executeCommand;
}
type RemoveFromRunResult = {
    orderId: string;
    runId: string;
    status: 'paid';
    codReleased: number;
    codTotal: number;
    collectedTotal: number;
};
export {};
