import { CorsOptions } from '@nestjs/common/interfaces/external/cors-options.interface';
import { HelmetOptions } from 'helmet';
import type { RequestHandler } from 'express';
export type RuntimeEnvReader = (name: string) => string | undefined;
export declare function resolveCorsOptions(env: RuntimeEnvReader): CorsOptions;
export declare function resolveHelmetOptions(env: RuntimeEnvReader): HelmetOptions;
export declare function resolveTrustProxy(env: RuntimeEnvReader): number | false;
export declare function isPublicHostname(host: string): boolean;
export declare function assertProductionModeForPublicHost(env: RuntimeEnvReader, host: string): void;
export declare function resolveAllowedHosts(env: RuntimeEnvReader): string[];
export declare function allowedHostsMiddleware(env: RuntimeEnvReader): RequestHandler;
