import { AuditService } from '../audit/audit.service';
import { PrismaService } from '../prisma/prisma.service';
import { RequestProtectionDto, UpdateProtectionDto } from './protection.dto';
export declare class ProtectionService {
    private readonly prisma;
    private readonly audit;
    constructor(prisma: PrismaService, audit: AuditService);
    mine(customerId: string): import(".prisma/client").Prisma.PrismaPromise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.ProtectionStatus;
        createdAt: Date;
        updatedAt: Date;
        imei: string;
        customerId: string;
        startsAt: Date | null;
        endsAt: Date | null;
        coverageMonths: number;
        staffNote: string | null;
        planType: string;
        premium: number | null;
        productName: string;
        deviceValue: number;
    }[]>;
    list(): import(".prisma/client").Prisma.PrismaPromise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.ProtectionStatus;
        createdAt: Date;
        updatedAt: Date;
        imei: string;
        customerId: string;
        startsAt: Date | null;
        endsAt: Date | null;
        coverageMonths: number;
        staffNote: string | null;
        planType: string;
        premium: number | null;
        productName: string;
        deviceValue: number;
    }[]>;
    request(customerId: string, dto: RequestProtectionDto): Promise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.ProtectionStatus;
        createdAt: Date;
        updatedAt: Date;
        imei: string;
        customerId: string;
        startsAt: Date | null;
        endsAt: Date | null;
        coverageMonths: number;
        staffNote: string | null;
        planType: string;
        premium: number | null;
        productName: string;
        deviceValue: number;
    }>;
    update(id: string, dto: UpdateProtectionDto, actor: string): Promise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.ProtectionStatus;
        createdAt: Date;
        updatedAt: Date;
        imei: string;
        customerId: string;
        startsAt: Date | null;
        endsAt: Date | null;
        coverageMonths: number;
        staffNote: string | null;
        planType: string;
        premium: number | null;
        productName: string;
        deviceValue: number;
    }>;
    accept(id: string, customerId: string): Promise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.ProtectionStatus;
        createdAt: Date;
        updatedAt: Date;
        imei: string;
        customerId: string;
        startsAt: Date | null;
        endsAt: Date | null;
        coverageMonths: number;
        staffNote: string | null;
        planType: string;
        premium: number | null;
        productName: string;
        deviceValue: number;
    }>;
    private event;
}
