import { AuthPrincipal } from '../auth/jwt.strategy';
import { RequestProtectionDto, UpdateProtectionDto } from './protection.dto';
import { ProtectionService } from './protection.service';
export declare class ProtectionController {
    private readonly protection;
    constructor(protection: ProtectionService);
    mine(user: AuthPrincipal): import(".prisma/client").Prisma.PrismaPromise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.ProtectionStatus;
        createdAt: Date;
        updatedAt: Date;
        imei: string;
        customerId: string;
        startsAt: Date | null;
        endsAt: Date | null;
        coverageMonths: number;
        staffNote: string | null;
        planType: string;
        premium: number | null;
        productName: string;
        deviceValue: number;
    }[]>;
    request(user: AuthPrincipal, dto: RequestProtectionDto): Promise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.ProtectionStatus;
        createdAt: Date;
        updatedAt: Date;
        imei: string;
        customerId: string;
        startsAt: Date | null;
        endsAt: Date | null;
        coverageMonths: number;
        staffNote: string | null;
        planType: string;
        premium: number | null;
        productName: string;
        deviceValue: number;
    }>;
    accept(user: AuthPrincipal, id: string): Promise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.ProtectionStatus;
        createdAt: Date;
        updatedAt: Date;
        imei: string;
        customerId: string;
        startsAt: Date | null;
        endsAt: Date | null;
        coverageMonths: number;
        staffNote: string | null;
        planType: string;
        premium: number | null;
        productName: string;
        deviceValue: number;
    }>;
    list(): import(".prisma/client").Prisma.PrismaPromise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.ProtectionStatus;
        createdAt: Date;
        updatedAt: Date;
        imei: string;
        customerId: string;
        startsAt: Date | null;
        endsAt: Date | null;
        coverageMonths: number;
        staffNote: string | null;
        planType: string;
        premium: number | null;
        productName: string;
        deviceValue: number;
    }[]>;
    update(user: AuthPrincipal, id: string, dto: UpdateProtectionDto): Promise<{
        id: string;
        orderId: string;
        status: import(".prisma/client").$Enums.ProtectionStatus;
        createdAt: Date;
        updatedAt: Date;
        imei: string;
        customerId: string;
        startsAt: Date | null;
        endsAt: Date | null;
        coverageMonths: number;
        staffNote: string | null;
        planType: string;
        premium: number | null;
        productName: string;
        deviceValue: number;
    }>;
    private customerId;
}
