import { OnModuleInit } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { AuditService } from '../audit/audit.service';
import { AuthzService } from '../authz/authz.service';
import { ApprovalsService } from '../approvals/approvals.service';
import { PrismaService } from '../prisma/prisma.service';
import { ReportsService } from '../reports/reports.service';
import { SupportService } from '../support/support.service';
import { StaffAuthService } from '../staff-auth/staff-auth.service';
import { OutboxService } from '../outbox/outbox.service';
export declare class TelegramAgentService implements OnModuleInit {
    private readonly prisma;
    private readonly config;
    private readonly outbox;
    private readonly audit;
    private readonly authz;
    private readonly reports;
    private readonly support;
    private readonly staffAuth;
    private readonly approvals;
    private readonly logger;
    private readonly client;
    private readonly enabled;
    private readonly webhookSecret;
    private readonly botToken;
    private readonly webhookUrl;
    private readonly miniAppUrl;
    private readonly model?;
    private readonly nodeEnv;
    private readonly certified;
    private readonly customerAiEnabled;
    private readonly customerAiDataCertified;
    private readonly ownerKillSwitch;
    constructor(prisma: PrismaService, config: ConfigService, outbox: OutboxService, audit: AuditService, authz: AuthzService, reports: ReportsService, support: SupportService, staffAuth: StaffAuthService, approvals: ApprovalsService);
    onModuleInit(): void;
    createPairing(staffId: string, totpToken?: string): Promise<{
        code: string;
        expiresAt: Date;
        command: string;
        warning: string;
    }>;
    disconnect(staffId: string, totpToken?: string): Promise<{
        disconnected: boolean;
    }>;
    handleWebhook(secret: string | undefined, rawUpdate: unknown): Promise<{
        ok: true;
    }>;
    private processMessage;
    private claimInbound;
    private consumePairing;
    private autoLinkCustomer;
    private answerCustomer;
    private answerStaff;
    private staffReadTools;
    private requireCapability;
    private requireApprovedWrite;
    private requestWriteApproval;
    private executeApprovedWrite;
    private requirePermission;
    private auditStaffRead;
    private auditDecision;
    private reply;
    private replyIdentityIsActive;
    private assertEnabled;
    private assertWebhookSecret;
    private unlinkedMessage;
    private assertRuntimeConfiguration;
}
