import { HrAbsenceStatus, Prisma } from '@prisma/client';
import { SettingsService } from '../settings/settings.service';
import { AuditService } from '../audit/audit.service';
import { PrismaService } from '../prisma/prisma.service';
import { CreateHrScheduleDto, RequestHrAbsenceDto, UpdateHrScheduleDto } from './hr.dto';
export declare class HrService {
    private readonly prisma;
    private readonly audit;
    private readonly settings;
    constructor(prisma: PrismaService, audit: AuditService, settings: SettingsService);
    private payrollConfig;
    private calculatePayroll;
    payrollPreview(period: string, point: string): Promise<{
        period: string;
        point: string;
        config: {
            baseAmount: number;
            commissionBps: number;
            latePenaltyPerMinute: number;
            overtimePayPerMinute: number;
        };
        lines: {
            staffId: string;
            username: string;
            plannedShifts: number;
            completedShifts: number;
            paidAbsenceShifts: number;
            workedMinutes: number;
            lateMinutes: number;
            overtimeMinutes: number;
            revenue: number;
            sales: number;
            baseEarned: number;
            commission: number;
            lateDeduction: number;
            overtimePay: number;
            total: number;
        }[];
        totals: {
            base: number;
            commission: number;
            adjustments: number;
            payout: number;
        };
    }>;
    payrollRuns(period: string, rawPoint: string): Promise<({
        lines: {
            id: string;
            createdAt: Date;
            revenue: number;
            username: string;
            staffId: string;
            total: number;
            runId: string;
            sales: number;
            plannedShifts: number;
            completedShifts: number;
            paidAbsenceShifts: number;
            workedMinutes: number;
            lateMinutes: number;
            overtimeMinutes: number;
            baseEarned: number;
            commission: number;
            lateDeduction: number;
            overtimePay: number;
        }[];
    } & {
        id: string;
        point: string;
        baseAmount: number;
        createdBy: string;
        status: import(".prisma/client").$Enums.HrPayrollStatus;
        createdAt: Date;
        period: string;
        updatedAt: Date;
        commissionBps: number;
        externalRef: string | null;
        paidBy: string | null;
        paidAt: Date | null;
        latePenaltyPerMinute: number;
        overtimePayPerMinute: number;
        totalBase: number;
        totalCommission: number;
        totalAdjustments: number;
        totalPayout: number;
        accrualAccountingEntryId: string | null;
        payoutAccountingEntryId: string | null;
    })[]>;
    postPayroll(period: string, rawPoint: string, actor: string, rawKey?: string): Promise<Prisma.InputJsonValue | null>;
    payPayroll(runId: string, rawExternalRef: string, actor: string, rawKey?: string, rawFundingAccountCode?: string): Promise<Prisma.InputJsonValue | null>;
    week(weekStart: string, point?: string, staffId?: string): Promise<{
        weekStart: Date;
        weekEnd: Date;
        point: string | null;
        staff: {
            id: string;
            active: boolean;
            username: string;
            role: import(".prisma/client").$Enums.Role;
        }[];
        schedules: ({
            attendance: {
                id: string;
                point: string;
                createdAt: Date;
                updatedAt: Date;
                staffId: string;
                scheduleId: string;
                checkedInAt: Date;
                checkedOutAt: Date | null;
                checkInKey: string;
                checkOutKey: string | null;
            } | null;
        } & {
            id: string;
            idempotencyKey: string;
            point: string;
            createdBy: string;
            createdAt: Date;
            updatedAt: Date;
            staffId: string;
            startsAt: Date;
            endsAt: Date;
            shiftDate: Date;
            cancelledAt: Date | null;
            cancelledBy: string | null;
            cancelReason: string | null;
        })[];
        absences: {
            id: string;
            type: import(".prisma/client").$Enums.HrAbsenceType;
            idempotencyKey: string;
            createdBy: string;
            status: import(".prisma/client").$Enums.HrAbsenceStatus;
            createdAt: Date;
            updatedAt: Date;
            staffId: string;
            reason: string | null;
            startsOn: Date;
            endsOn: Date;
            decidedBy: string | null;
            decidedAt: Date | null;
            decisionNote: string | null;
        }[];
        timesheet: {
            staffId: string;
            username: string;
            shifts: number;
            minutes: number;
            lateMinutes: number;
            overtimeMinutes: number;
        }[];
    }>;
    createSchedule(dto: CreateHrScheduleDto, actor: string, rawKey?: string): Promise<{
        id: string;
        idempotencyKey: string;
        point: string;
        createdBy: string;
        createdAt: Date;
        updatedAt: Date;
        staffId: string;
        startsAt: Date;
        endsAt: Date;
        shiftDate: Date;
        cancelledAt: Date | null;
        cancelledBy: string | null;
        cancelReason: string | null;
    }>;
    updateSchedule(id: string, dto: UpdateHrScheduleDto, actor: string, rawKey?: string): Promise<Prisma.InputJsonValue | null>;
    cancelSchedule(id: string, reason: string | undefined, actor: string, rawKey?: string): Promise<Prisma.InputJsonValue | null>;
    openAttendance(scheduleId: string, staffId: string, rawKey?: string): Promise<{
        id: string;
        point: string;
        createdAt: Date;
        updatedAt: Date;
        staffId: string;
        scheduleId: string;
        checkedInAt: Date;
        checkedOutAt: Date | null;
        checkInKey: string;
        checkOutKey: string | null;
    }>;
    closeAttendance(scheduleId: string, staffId: string, rawKey?: string): Promise<{
        id: string;
        point: string;
        createdAt: Date;
        updatedAt: Date;
        staffId: string;
        scheduleId: string;
        checkedInAt: Date;
        checkedOutAt: Date | null;
        checkInKey: string;
        checkOutKey: string | null;
    }>;
    requestAbsence(dto: RequestHrAbsenceDto, staffId: string, rawKey?: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.HrAbsenceType;
        idempotencyKey: string;
        createdBy: string;
        status: import(".prisma/client").$Enums.HrAbsenceStatus;
        createdAt: Date;
        updatedAt: Date;
        staffId: string;
        reason: string | null;
        startsOn: Date;
        endsOn: Date;
        decidedBy: string | null;
        decidedAt: Date | null;
        decisionNote: string | null;
    }>;
    decideAbsence(id: string, status: HrAbsenceStatus, note: string | undefined, actor: string): Promise<{
        id: string;
        type: import(".prisma/client").$Enums.HrAbsenceType;
        idempotencyKey: string;
        createdBy: string;
        status: import(".prisma/client").$Enums.HrAbsenceStatus;
        createdAt: Date;
        updatedAt: Date;
        staffId: string;
        reason: string | null;
        startsOn: Date;
        endsOn: Date;
        decidedBy: string | null;
        decidedAt: Date | null;
        decisionNote: string | null;
    }>;
}
