import { Prisma } from '@prisma/client';
import { AuditService } from '../audit/audit.service';
import { CatalogService } from '../catalog/catalog.service';
import { ModerationService } from '../ai/moderation.service';
import { PrismaService } from '../prisma/prisma.service';
import { CreateStorefrontContentDto, ScheduleStorefrontContentDto } from './storefront.dto';
export declare class StorefrontService {
    private readonly prisma;
    private readonly audit;
    private readonly catalog;
    private readonly moderation;
    constructor(prisma: PrismaService, audit: AuditService, catalog: CatalogService, moderation: ModerationService);
    publicContent(): Promise<{
        content: {
            readonly id: "fallback";
            readonly version: 0;
            readonly status: "published";
            readonly heroEyebrow: "Доставка 1–2 часа по Манасу";
            readonly heroTitle: "Техника с гарантией. Новое и Б/У.";
            readonly heroBody: "Рассрочка 0%, trade-in старого устройства, один профиль и корзина на сайте и в приложении.";
            readonly heroCtaLabel: "В каталог";
            readonly heroCtaHref: "/catalog";
            readonly heroImageUrl: null;
            readonly financingText: null;
            readonly aboutTitle: "О AliStore";
            readonly aboutBody: "AliStore объединяет интернет-магазин, склад, сервис и торговую точку в одной системе. На сайте публикуются только товары и условия, подтверждённые операционными данными.";
            readonly deliveryTitle: "Доставка и получение";
            readonly deliveryBody: "Доступные точки, зоны, стоимость и интервалы показываются при оформлении заказа. Итоговые условия подтверждает сервер до оплаты.";
            readonly contactPhone: null;
            readonly supportHours: null;
            readonly featuredTitle: "Популярное";
            readonly featuredProductIds: readonly [];
            readonly benefits: readonly [{
                readonly title: "Актуальное наличие";
                readonly body: "Остаток поступает из складской системы";
            }, {
                readonly title: "Прозрачное оформление";
                readonly body: "Цена и доставка подтверждаются до оплаты";
            }];
            readonly publishedAt: null;
            readonly startsAt: null;
            readonly endsAt: null;
        } | {
            publishedAt: string | null;
            startsAt: string | null;
            endsAt: string | null;
            id: string;
            version: number;
            status: string;
            heroEyebrow: string;
            heroTitle: string;
            heroBody: string;
            heroCtaLabel: string;
            heroCtaHref: string;
            heroImageUrl: string | null;
            financingText: string | null;
            aboutTitle: string;
            aboutBody: string;
            deliveryTitle: string;
            deliveryBody: string;
            contactPhone: string | null;
            supportHours: string | null;
            benefits: Prisma.JsonValue;
            featuredTitle: string;
            featuredProductIds: string[];
        };
        stores: {
            id: string;
            name: string;
            code: string;
            hours: string;
            address: string;
        }[];
        featuredProducts: import("../catalog/catalog.dto").CatalogProductDto[];
    }>;
    list(): Prisma.PrismaPromise<{
        id: string;
        createdBy: string;
        status: string;
        createdAt: Date;
        version: number;
        startsAt: Date | null;
        endsAt: Date | null;
        heroEyebrow: string;
        heroTitle: string;
        heroBody: string;
        heroCtaLabel: string;
        heroCtaHref: string;
        heroImageUrl: string | null;
        financingText: string | null;
        aboutTitle: string;
        aboutBody: string;
        deliveryTitle: string;
        deliveryBody: string;
        contactPhone: string | null;
        supportHours: string | null;
        benefits: Prisma.JsonValue;
        featuredTitle: string;
        featuredProductIds: string[];
        publishedBy: string | null;
        scheduledBy: string | null;
        publishedAt: Date | null;
    }[]>;
    createDraft(dto: CreateStorefrontContentDto, actor: string): Promise<{
        id: string;
        createdBy: string;
        status: string;
        createdAt: Date;
        version: number;
        startsAt: Date | null;
        endsAt: Date | null;
        heroEyebrow: string;
        heroTitle: string;
        heroBody: string;
        heroCtaLabel: string;
        heroCtaHref: string;
        heroImageUrl: string | null;
        financingText: string | null;
        aboutTitle: string;
        aboutBody: string;
        deliveryTitle: string;
        deliveryBody: string;
        contactPhone: string | null;
        supportHours: string | null;
        benefits: Prisma.JsonValue;
        featuredTitle: string;
        featuredProductIds: string[];
        publishedBy: string | null;
        scheduledBy: string | null;
        publishedAt: Date | null;
    }>;
    publish(id: string, actor: string): Promise<{
        id: string;
        createdBy: string;
        status: string;
        createdAt: Date;
        version: number;
        startsAt: Date | null;
        endsAt: Date | null;
        heroEyebrow: string;
        heroTitle: string;
        heroBody: string;
        heroCtaLabel: string;
        heroCtaHref: string;
        heroImageUrl: string | null;
        financingText: string | null;
        aboutTitle: string;
        aboutBody: string;
        deliveryTitle: string;
        deliveryBody: string;
        contactPhone: string | null;
        supportHours: string | null;
        benefits: Prisma.JsonValue;
        featuredTitle: string;
        featuredProductIds: string[];
        publishedBy: string | null;
        scheduledBy: string | null;
        publishedAt: Date | null;
    }>;
    schedule(id: string, dto: ScheduleStorefrontContentDto, actor: string): Promise<{
        id: string;
        createdBy: string;
        status: string;
        createdAt: Date;
        version: number;
        startsAt: Date | null;
        endsAt: Date | null;
        heroEyebrow: string;
        heroTitle: string;
        heroBody: string;
        heroCtaLabel: string;
        heroCtaHref: string;
        heroImageUrl: string | null;
        financingText: string | null;
        aboutTitle: string;
        aboutBody: string;
        deliveryTitle: string;
        deliveryBody: string;
        contactPhone: string | null;
        supportHours: string | null;
        benefits: Prisma.JsonValue;
        featuredTitle: string;
        featuredProductIds: string[];
        publishedBy: string | null;
        scheduledBy: string | null;
        publishedAt: Date | null;
    }>;
    cancelSchedule(id: string, actor: string): Promise<{
        id: string;
        createdBy: string;
        status: string;
        createdAt: Date;
        version: number;
        startsAt: Date | null;
        endsAt: Date | null;
        heroEyebrow: string;
        heroTitle: string;
        heroBody: string;
        heroCtaLabel: string;
        heroCtaHref: string;
        heroImageUrl: string | null;
        financingText: string | null;
        aboutTitle: string;
        aboutBody: string;
        deliveryTitle: string;
        deliveryBody: string;
        contactPhone: string | null;
        supportHours: string | null;
        benefits: Prisma.JsonValue;
        featuredTitle: string;
        featuredProductIds: string[];
        publishedBy: string | null;
        scheduledBy: string | null;
        publishedAt: Date | null;
    }>;
    private normalize;
    private assertFeaturedProducts;
    private assertContentClean;
    private benefit;
    private safeUrl;
    private publicView;
}
