import { AuthPrincipal } from '../auth/jwt.strategy';
import { CreateStorefrontContentDto, ScheduleStorefrontContentDto } from './storefront.dto';
import { ApprovalsService } from '../approvals/approvals.service';
import { StorefrontService } from './storefront.service';
export declare class StorefrontPublicController {
    private readonly storefront;
    constructor(storefront: StorefrontService);
    content(): Promise<{
        content: {
            readonly id: "fallback";
            readonly version: 0;
            readonly status: "published";
            readonly heroEyebrow: "Доставка 1–2 часа по Манасу";
            readonly heroTitle: "Техника с гарантией. Новое и Б/У.";
            readonly heroBody: "Рассрочка 0%, trade-in старого устройства, один профиль и корзина на сайте и в приложении.";
            readonly heroCtaLabel: "В каталог";
            readonly heroCtaHref: "/catalog";
            readonly heroImageUrl: null;
            readonly financingText: null;
            readonly aboutTitle: "О AliStore";
            readonly aboutBody: "AliStore объединяет интернет-магазин, склад, сервис и торговую точку в одной системе. На сайте публикуются только товары и условия, подтверждённые операционными данными.";
            readonly deliveryTitle: "Доставка и получение";
            readonly deliveryBody: "Доступные точки, зоны, стоимость и интервалы показываются при оформлении заказа. Итоговые условия подтверждает сервер до оплаты.";
            readonly contactPhone: null;
            readonly supportHours: null;
            readonly featuredTitle: "Популярное";
            readonly featuredProductIds: readonly [];
            readonly benefits: readonly [{
                readonly title: "Актуальное наличие";
                readonly body: "Остаток поступает из складской системы";
            }, {
                readonly title: "Прозрачное оформление";
                readonly body: "Цена и доставка подтверждаются до оплаты";
            }];
            readonly publishedAt: null;
            readonly startsAt: null;
            readonly endsAt: null;
        } | {
            publishedAt: string | null;
            startsAt: string | null;
            endsAt: string | null;
            id: string;
            version: number;
            status: string;
            heroEyebrow: string;
            heroTitle: string;
            heroBody: string;
            heroCtaLabel: string;
            heroCtaHref: string;
            heroImageUrl: string | null;
            financingText: string | null;
            aboutTitle: string;
            aboutBody: string;
            deliveryTitle: string;
            deliveryBody: string;
            contactPhone: string | null;
            supportHours: string | null;
            benefits: import("@prisma/client/runtime/library").JsonValue;
            featuredTitle: string;
            featuredProductIds: string[];
        };
        stores: {
            id: string;
            name: string;
            code: string;
            hours: string;
            address: string;
        }[];
        featuredProducts: import("../catalog/catalog.dto").CatalogProductDto[];
    }>;
}
export declare class StorefrontAdminController {
    private readonly storefront;
    private readonly approvals;
    constructor(storefront: StorefrontService, approvals: ApprovalsService);
    list(): import(".prisma/client").Prisma.PrismaPromise<{
        id: string;
        createdBy: string;
        status: string;
        createdAt: Date;
        version: number;
        startsAt: Date | null;
        endsAt: Date | null;
        heroEyebrow: string;
        heroTitle: string;
        heroBody: string;
        heroCtaLabel: string;
        heroCtaHref: string;
        heroImageUrl: string | null;
        financingText: string | null;
        aboutTitle: string;
        aboutBody: string;
        deliveryTitle: string;
        deliveryBody: string;
        contactPhone: string | null;
        supportHours: string | null;
        benefits: import("@prisma/client/runtime/library").JsonValue;
        featuredTitle: string;
        featuredProductIds: string[];
        publishedBy: string | null;
        scheduledBy: string | null;
        publishedAt: Date | null;
    }[]>;
    create(user: AuthPrincipal, dto: CreateStorefrontContentDto): Promise<{
        id: string;
        createdBy: string;
        status: string;
        createdAt: Date;
        version: number;
        startsAt: Date | null;
        endsAt: Date | null;
        heroEyebrow: string;
        heroTitle: string;
        heroBody: string;
        heroCtaLabel: string;
        heroCtaHref: string;
        heroImageUrl: string | null;
        financingText: string | null;
        aboutTitle: string;
        aboutBody: string;
        deliveryTitle: string;
        deliveryBody: string;
        contactPhone: string | null;
        supportHours: string | null;
        benefits: import("@prisma/client/runtime/library").JsonValue;
        featuredTitle: string;
        featuredProductIds: string[];
        publishedBy: string | null;
        scheduledBy: string | null;
        publishedAt: Date | null;
    }>;
    publish(user: AuthPrincipal, id: string): Promise<{
        action: string;
        approvalId: string;
        status: "requested";
    }>;
    schedule(user: AuthPrincipal, id: string, dto: ScheduleStorefrontContentDto): Promise<{
        id: string;
        createdBy: string;
        status: string;
        createdAt: Date;
        version: number;
        startsAt: Date | null;
        endsAt: Date | null;
        heroEyebrow: string;
        heroTitle: string;
        heroBody: string;
        heroCtaLabel: string;
        heroCtaHref: string;
        heroImageUrl: string | null;
        financingText: string | null;
        aboutTitle: string;
        aboutBody: string;
        deliveryTitle: string;
        deliveryBody: string;
        contactPhone: string | null;
        supportHours: string | null;
        benefits: import("@prisma/client/runtime/library").JsonValue;
        featuredTitle: string;
        featuredProductIds: string[];
        publishedBy: string | null;
        scheduledBy: string | null;
        publishedAt: Date | null;
    }>;
    cancelSchedule(user: AuthPrincipal, id: string): Promise<{
        id: string;
        createdBy: string;
        status: string;
        createdAt: Date;
        version: number;
        startsAt: Date | null;
        endsAt: Date | null;
        heroEyebrow: string;
        heroTitle: string;
        heroBody: string;
        heroCtaLabel: string;
        heroCtaHref: string;
        heroImageUrl: string | null;
        financingText: string | null;
        aboutTitle: string;
        aboutBody: string;
        deliveryTitle: string;
        deliveryBody: string;
        contactPhone: string | null;
        supportHours: string | null;
        benefits: import("@prisma/client/runtime/library").JsonValue;
        featuredTitle: string;
        featuredProductIds: string[];
        publishedBy: string | null;
        scheduledBy: string | null;
        publishedAt: Date | null;
    }>;
}
