import { Prisma } from '@prisma/client';
import { AuditInput } from '../audit/audit.service';
export declare function publishStorefrontRevisionOnTx(tx: Prisma.TransactionClient, revisionId: string, actor: string, events: AuditInput[]): Promise<{
    id: string;
    createdBy: string;
    status: string;
    createdAt: Date;
    version: number;
    startsAt: Date | null;
    endsAt: Date | null;
    heroEyebrow: string;
    heroTitle: string;
    heroBody: string;
    heroCtaLabel: string;
    heroCtaHref: string;
    heroImageUrl: string | null;
    financingText: string | null;
    aboutTitle: string;
    aboutBody: string;
    deliveryTitle: string;
    deliveryBody: string;
    contactPhone: string | null;
    supportHours: string | null;
    benefits: Prisma.JsonValue;
    featuredTitle: string;
    featuredProductIds: string[];
    publishedBy: string | null;
    scheduledBy: string | null;
    publishedAt: Date | null;
}>;
